const range=(key,label,min,max,value,unit='',step=1)=>({key,label,min,max,value,unit,step,type:'range'});
const toggle=(key,label,value)=>({key,label,value,type:'checkbox'});
const select=(key,label,options,value)=>({key,label,options,value,type:'select'});
const color=(key,label,value)=>({key,label,value,type:'color'});
const text=(key,label,value)=>({key,label,value,type:'text'});
const systemFaceGroups=[
['Sans serif',[
['System sans',"ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"],
['Arial','Arial, Helvetica, sans-serif'],
['Helvetica',"'Helvetica Neue', Helvetica, Arial, sans-serif"],
['Verdana','Verdana, Geneva, sans-serif'],
['Tahoma','Tahoma, Verdana, sans-serif'],
['Trebuchet MS',"'Trebuchet MS', sans-serif"],
['Gill Sans',"'Gill Sans', 'Gill Sans MT', Calibri, sans-serif"],
['Segoe UI',"'Segoe UI', sans-serif"],
['Calibri','Calibri, Candara, sans-serif'],
['Avenir',"Avenir, 'Avenir Next', sans-serif"],
['Futura',"Futura, 'Trebuchet MS', sans-serif"],
['Optima','Optima, Candara, sans-serif'],
['Lucida Sans',"'Lucida Sans', 'Lucida Grande', 'Lucida Sans Unicode', sans-serif"],
['Century Gothic',"'Century Gothic', CenturyGothic, sans-serif"]
]],
['Serif',[
['System serif',"ui-serif, Georgia, 'Times New Roman', serif"],
['Georgia','Georgia, serif'],
['Times New Roman',"'Times New Roman', Times, serif"],
['Palatino',"Palatino, 'Palatino Linotype', 'Book Antiqua', serif"],
['Garamond',"Garamond, 'Palatino Linotype', serif"],
['Baskerville','Baskerville, Georgia, serif'],
['Cambria','Cambria, Georgia, serif'],
['Didot',"Didot, 'Bodoni MT', serif"],
['Rockwell','Rockwell, Georgia, serif'],
['American Typewriter',"'American Typewriter', Courier, serif"],
['Charter',"Charter, 'Bitstream Charter', Georgia, serif"],
['Hoefler Text',"'Hoefler Text', Garamond, serif"],
['Iowan Old Style',"'Iowan Old Style', Palatino, serif"]
]],
['Monospace',[
['System mono',"ui-monospace, 'SF Mono', Menlo, Consolas, monospace"],
['Courier New',"'Courier New', Courier, monospace"],
['Menlo','Menlo, Monaco, Consolas, monospace'],
['Monaco','Monaco, Menlo, Consolas, monospace'],
['Consolas','Consolas, Menlo, Monaco, monospace'],
['Lucida Console',"'Lucida Console', Monaco, monospace"]
]],
['Display and script',[
['Impact',"Impact, 'Arial Narrow', sans-serif"],
['Comic Sans MS',"'Comic Sans MS', 'Comic Sans', cursive"],
['Brush Script',"'Brush Script MT', cursive"],
['Papyrus','Papyrus, fantasy']
]]
];
const systemFaceStack=Object.fromEntries(systemFaceGroups.flatMap(group=>group[1]));
const lessons=[
{group:'Visual foundations',title:'Typography',description:'Typography is how you shape written information using font, size, weight, and line height. Good typography helps people read comfortably and distinguish headings from supporting details. A larger font is not automatically better: the relationship between sizes and the space between lines matters.',challenge:'Set the body text to 18px. Then squeeze the line height and notice when reading becomes harder. Switch between a sans, a serif, and a monospace face.',notice:'Look at how many words fit on each line and whether your eye can find the next line easily. The same words change width and tone when the typeface changes. A listed face appears only when it is installed on this computer. Keep body text comfortably readable and use a clear difference between headings and body text.',controls:[range('size','Body size',12,26,16,'px'),range('leading','Line height',1,2.2,1.6,'',.1),select('font','Typeface',systemFaceGroups.map(group=>({label:group[0],items:group[1].map(face=>face[0])})),'System sans'),range('heading','Heading size',18,44,28,'px')],kind:'type'},
{group:'Visual foundations',title:'Color & contrast',description:'Color can communicate emphasis, mood, and status. Contrast is the difference in luminance between foreground and background; it affects whether text is readable. Do not rely on color alone to communicate an error or success: include words or another visible cue.',challenge:'Choose similar text and background colors, then increase their difference until the normal-text AA check passes.',notice:'The ratio below is calculated from your selected colors. WCAG AA requires at least 4.5:1 for normal text and 3:1 for large text. Passing one color pair does not establish that an entire interface is accessible.',controls:[color('fg','Text color','#243044'),color('bg','Background','#ffffff'),color('accent','Button color','#2334ea')],kind:'color'},
{group:'Visual foundations',title:'Spacing & proximity',description:'Spacing determines how crowded an interface feels. Proximity creates relationships: items placed close together usually look related. Keep a label near its field, and leave more space between separate groups than between items within a group.',challenge:'Make the gap between fields smaller than the gap between sections. Then reverse the relationship.',notice:'You should be able to see which label belongs to which field without drawing an imaginary line. Large amounts of space are useful only when they clarify a relationship or improve comfort.',controls:[range('padding','Outer padding',8,48,28,'px'),range('gap','Within a group',2,32,8,'px'),range('section','Between groups',4,56,28,'px')],kind:'spacing'},
{group:'Visual foundations',title:'Columns & layout',description:'Layout gives information a structure. Columns can make related items easier to compare, but too many columns squeeze content and slow scanning. Choose the arrangement around what people need to read or compare, rather than filling every available inch.',challenge:'Compare one and three columns. Increase the gap and watch how the available reading space changes.',notice:'Columns work when each item still has enough width. A real responsive layout usually reduces the column count as available space shrinks.',controls:[range('columns','Columns',1,3,2),range('gap','Column gap',4,32,16,'px'),select('align','Text alignment',['Left','Center'],'Left')],kind:'columns'},
{group:'Visual foundations',title:'Visual hierarchy',description:'Visual hierarchy is the order in which elements attract attention. Size, weight, contrast, position, and spacing help users distinguish the main heading, essential information, and primary action. If everything is emphasized equally, users have to decide what matters for themselves.',challenge:'Turn off hierarchy and make both actions equally prominent. Then restore the differences.',notice:'Can you tell what the page is about and which action is recommended within a quick glance? Hierarchy should reflect importance, not decoration.',controls:[toggle('hierarchy','Clear text hierarchy',true),toggle('action','Emphasize main action',true),range('title','Title size',16,40,28,'px')],kind:'hierarchy'},
{group:'Visual foundations',title:'Alignment & density',description:'Alignment gives elements a shared visual anchor, which makes a page feel organized and easier to scan. Density describes how much information occupies a given space. Dense interfaces can help experienced users compare many records, while more generous layouts can make individual items easier to read or tap.',challenge:'Switch between compact and spacious rows. Compare a shared left edge with centered text.',notice:'Find an item and its action. Does your eye follow a predictable path? More compact is useful only if it still supports reading and accurate interaction.',controls:[range('padding','Row padding',4,28,14,'px'),select('align','Alignment',['Left','Center'],'Left'),toggle('lines','Row separators',true)],kind:'density'},
{group:'Structure & words',title:'User experience',description:'User experience concerns whether people can accomplish their goal and how the whole journey feels. It includes finding the right place, understanding choices, completing the task, and knowing the outcome. Optimizing a single button is not enough if the workflow requires unnecessary steps.',challenge:'Complete a reservation with the extra review step enabled, then reset and remove it. Is the extra step useful for this task?',notice:'Fewer steps can reduce effort, but a review step may prevent a costly mistake. Judge the flow by the user’s goal and consequences, rather than by click count alone.',controls:[toggle('extra','Require a review step',true)],kind:'ux'},
{group:'Structure & words',title:'Information architecture',description:'Information architecture is how you group, name, and connect information. Useful categories match the way people think about their task. Navigation labels should help users predict what is inside before opening a section.',challenge:'Find the upcoming workshop using vague labels, then enable clear categories and try again.',notice:'Compare the effort of guessing with the effort of recognizing. An unfamiliar category can be technically accurate while still being a poor navigation label.',controls:[toggle('clear','Use clear categories',true)],kind:'ia'},
{group:'Structure & words',title:'Content design',description:'Content design uses words to help people understand and act. Labels should describe what an action will do; instructions should explain necessary steps; errors should say what went wrong and how to fix it. Good wording reduces the amount of interpretation the interface demands.',challenge:'Switch to vague labels and submit an empty name. Then restore specific wording and compare the error.',notice:'“Reserve a place” describes the result more clearly than “Continue.” Helpful errors identify the issue and give the user an achievable next step.',controls:[toggle('specific','Use specific wording',true),text('button','Specific action label','Reserve a place')],kind:'content'},
{group:'Behavior & feedback',title:'Recognizable controls',description:'Controls need to look and behave like things people can interact with. Buttons usually perform actions, links usually navigate, and checkboxes usually represent on-or-off choices. Familiar patterns reduce the need to experiment just to discover what is clickable.',challenge:'Remove the button styling. Can you still tell how to reserve a place before trying to click?',notice:'A control should be recognizable in its resting state, not only after hovering. Preserve keyboard access and a visible focus indicator as well as visual affordances.',controls:[toggle('recognizable','Visible button treatment',true),toggle('label','Descriptive action label',true)],kind:'controls'},
{group:'Behavior & feedback',title:'Visible system status',description:'Visible system status keeps people informed about what the interface is doing. When an action takes time, immediate feedback confirms that it was received; progress or a status message explains the wait; a success message confirms the result. Feedback should be timely and proportionate.',challenge:'Save with feedback disabled. Reset the experiment, enable feedback, and save again.',notice:'Without feedback, people may click repeatedly or wonder whether an action worked. The example simulates a three-second save; a real app should report its actual state.',controls:[toggle('feedback','Show saving and success',true)],kind:'status'},
{group:'Behavior & feedback',title:'Error prevention',description:'Error prevention reduces the chance of a mistake before it occurs. Clear constraints, useful defaults, input validation, and confirmation for consequential actions are common approaches. Use confirmation selectively: asking about every harmless action adds friction and teaches people to dismiss prompts.',challenge:'Delete the sample project with confirmation disabled, then reset and enable confirmation.',notice:'Ask whether the action’s cost justifies interrupting the user. A reversible action might be better served by undo; a permanent action often needs stronger protection.',controls:[toggle('confirm','Confirm before deletion',true)],kind:'prevention'},
{group:'Behavior & feedback',title:'Recovery & undo',description:'Recovery helps users regain control after a mistake. Undo, cancel, editable submissions, and clear recovery instructions reduce the cost of experimentation. The recovery option should be easy to find and accurately describe what it restores.',challenge:'Remove a task with undo disabled, then reset, enable undo, and restore it.',notice:'A success message alone cannot repair an accidental action. Check whether recovery actually restores the affected item and puts it back in the right place.',controls:[toggle('undo','Offer undo',true)],kind:'recovery'},
{group:'Inclusive & consistent',title:'Accessibility',description:'Accessibility means people with different abilities can perceive, understand, and operate an interface. Semantic HTML, keyboard operation, visible focus, readable contrast, and understandable labels all contribute. Accessibility is part of the design from the start, rather than a final visual check.',challenge:'Click the first field, then press Tab through the form. Compare focus visibility with it enabled and disabled.',notice:'The focus ring tells keyboard users where their next action will happen. Hidden focus in this isolated example demonstrates a problem; the playground controls themselves keep visible focus. This experiment is not a complete accessibility audit.',controls:[toggle('focus','Visible focus in example',true),range('target','Button height',24,60,44,'px')],kind:'access'},
{group:'Inclusive & consistent',title:'Responsive design',description:'Responsive design adapts an interface to the space available and the way people interact. A narrow screen often needs fewer columns and different grouping, rather than a miniature version of the desktop layout. Preserve the essential content and actions as the layout changes.',challenge:'Reduce the example width below 400px. Compare automatic stacking with a fixed three-column layout.',notice:'Watch whether each card remains readable and each button usable. This simulates available width; test real devices too, because touch, zoom, keyboards, and browser behavior also affect usability.',controls:[range('width','Example width',260,600,500,'px'),toggle('adapt','Adapt the columns',true)],kind:'responsive'},
{group:'Inclusive & consistent',title:'Consistency & design systems',description:'Consistency means similar things look and behave similarly, so people can reuse what they already learned. A design system makes those decisions reusable through shared tokens, components, and usage guidance. It covers behavior and content as well as colors and spacing.',challenge:'Disable shared styles to compare mismatched cards. Then change the shared accent and corner radius.',notice:'Repeated controls should mean the same thing and respond the same way. Shared tokens let you change a decision in one place without manually repairing each component.',controls:[toggle('shared','Use shared styles',true),color('accent','Shared accent','#2334ea'),range('radius','Shared corner radius',0,24,8,'px')],kind:'system'},
{group:'Evaluate the result',title:'Usability evaluation',description:'Usability evaluation checks whether people can complete tasks with the interface. Give someone a realistic goal and observe without coaching. Notice hesitation, wrong turns, and mistakes; ask what they expected. A successful self-test is useful practice, but it does not replace observing other users.',challenge:'Find the workshop reservation and complete it. Then switch the labels and ask someone else to try without hints.',notice:'Compare task completion, time, and confusion rather than asking only whether the page looks good. The timer below is a practice aid, not a scientifically controlled comparison.',controls:[toggle('clear','Clear navigation labels',true)],kind:'usability'},
{group:'Evaluate the result',title:'Nielsen’s review framework',description:'Nielsen’s ten usability heuristics are broad questions for reviewing an interface: status visibility, familiar language, user control, consistency, error prevention, recognition rather than recall, efficiency, minimalism, error recovery, and help. They guide inspection; they do not prove usability or replace testing with users.',challenge:'Toggle the protections and try saving or removing the project. Identify which heuristic each setting supports.',notice:'Use this as a small review example. A real heuristic review checks actual tasks and states across the interface, including failures. No single score here would establish usability.',controls:[toggle('feedback','Show system feedback',true),toggle('undo','Support undo',true),toggle('wording','Use familiar wording',true)],kind:'heuristics'}
,...createStyleLessons(),createWorkshopLesson()
];
let current=0,state={},timer=null,actionState={}; const $=id=>document.getElementById(id)||previewElement(id);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function optionList(options,value){const item=o=>'<option'+(o===value?' selected':'')+'>'+esc(o)+'</option>';if(options[0]&&typeof options[0]==='object')return options.map(g=>'<optgroup label="'+esc(g.label)+'">'+g.items.map(item).join('')+'</optgroup>').join('');return options.map(item).join('');}
function faceInstalled(name){const stack=systemFaceStack[name]||'';const primary=(stack.split(',')[0]||'').trim().replace(/^['"]|['"]$/g,'');if(!primary||/^(ui-[\w-]+|system-ui|-apple-system|BlinkMacSystemFont|sans-serif|serif|monospace|cursive|fantasy)$/.test(primary))return true;const canvas=faceInstalled.canvas||(faceInstalled.canvas=document.createElement('canvas'));const ctx=canvas.getContext('2d');if(!ctx)return true;const sample='mmmmmmmmmmlli';const width=font=>{ctx.font='72px '+font;return ctx.measureText(sample).width;};const quoted="'"+primary.replace(/'/g,'')+"'";const mono=width('monospace'),sans=width('sans-serif');return width(quoted+', monospace')!==mono||width(quoted+', sans-serif')!==sans;}
function card(){return '<h3>Make room for a new skill.</h3><p>Join a hands-on weekend workshop. Explore a new idea, work at your own pace, and leave with something you made.</p><p class="small">Saturday · 10:00 AM · 12 places available</p><button class="primary" data-act="reserve">Reserve a place</button>';}
function tiles(n=3){return Array.from({length:n},(_,i)=>'<div class="tile"><h4>'+['Creative writing','Photography','Printmaking'][i]+'</h4><p>'+['Find your voice.','See things differently.','Make an original print.'][i]+'</p></div>').join('');}
function luminance(hex){let rgb=hex.match(/\w\w/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];}
function ratio(a,b){let x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
function initialize(index){clearTimeout(timer);current=index;state=Object.fromEntries(lessons[index].controls.map(c=>[c.key,c.value]));actionState={};renderLesson();}
function renderLesson(){const l=lessons[current];setWorkshopMode(l.kind==='workshop');$('chapter').textContent=l.group+' / '+String(current+1).padStart(2,'0');$('title').textContent=l.title;$('description').textContent=l.description;$('challenge').textContent=l.challenge;$('notice').textContent=l.notice;$('position').textContent=(current+1)+' / '+lessons.length;$('previous').disabled=current===0;$('next').disabled=current===lessons.length-1;document.querySelectorAll('nav button').forEach((b,i)=>b.setAttribute('aria-current',i===current?'true':'false'));
$('controls').innerHTML=l.controls.map(c=>{let id='c-'+c.key,v=state[c.key],input;if(c.type==='select')input='<select id="'+id+'" data-key="'+c.key+'">'+optionList(c.options,v)+'</select>';else input='<input id="'+id+'" data-key="'+c.key+'" type="'+c.type+'" '+(c.type==='range'?'min="'+c.min+'" max="'+c.max+'" step="'+c.step+'" ':'')+(c.type==='checkbox'?(v?'checked':''):'value="'+esc(v)+'"')+'>';return '<div class="control"><label for="'+id+'">'+c.label+(c.type==='range'?'<output id="o-'+c.key+'">'+v+c.unit+'</output>':'')+(c.type==='checkbox'?input:'')+'</label>'+(c.type==='checkbox'?'':input)+'</div>';}).join('');renderPreview();}
function renderPreview(){const l=lessons[current],s=state;showWorkshopTools(l.kind,s);let h='',style='',extra='',k=l.kind;
if(k==='type'){style='font-size:'+s.size+'px;line-height:'+s.leading+';font-family:'+(systemFaceStack[s.font]||'inherit');h=card().replace('<h3>','<h3 style="font-size:'+s.heading+'px">');if(!faceInstalled(s.font))extra='<div class="legend">'+esc(s.font)+' is not installed on this computer, so the example uses the next available face.</div>';}
if(k==='color'){style='color:'+s.fg+';background:'+s.bg;let r=ratio(s.fg,s.bg),br=ratio('#ffffff',s.accent);h=card().replace('class="primary"','class="primary" style="background:'+s.accent+';border-color:'+s.accent+'"');extra='<div class="contrast-result">Text: <strong>'+r.toFixed(2)+':1</strong> · '+(r>=4.5?'Passes':'Below')+' normal-text AA<br>White button text: <strong>'+br.toFixed(2)+':1</strong> · '+(br>=4.5?'Passes':'Below')+' normal-text AA</div>';}
if(k==='spacing'){style='padding:'+s.padding+'px';h='<h3>Your reservation</h3><div style="margin-bottom:'+s.section+'px"><label style="margin-bottom:'+s.gap+'px" for="name">Your name</label><input id="name" placeholder="Alex Morgan"></div><div><label style="margin-bottom:'+s.gap+'px" for="email">Email address</label><input id="email" type="email" placeholder="alex@example.com"></div><button class="primary" style="margin-top:'+s.section+'px" data-act="reserve">Reserve a place</button>';}
if(k==='columns'){h='<h3>Choose a workshop</h3><div class="samplegrid" style="grid-template-columns:repeat('+s.columns+',minmax(0,1fr));gap:'+s.gap+'px;text-align:'+s.align.toLowerCase()+'">'+tiles()+'</div>';}
if(k==='hierarchy'){h='<p style="font-size:'+(s.hierarchy?12:16)+'px;font-weight:600;color:'+(s.hierarchy?'#657188':'inherit')+'">WEEKEND WORKSHOP</p><h3 style="font-size:'+(s.hierarchy?s.title:16)+'px;font-weight:'+(s.hierarchy?750:400)+'">Creative writing</h3><p>Find your voice in a small, welcoming group.</p><p class="small" style="'+(!s.hierarchy?'font-size:16px;color:inherit':'')+'">Saturday · 10:00 AM · $25</p><div class="row"><button '+(s.action?'class="primary"':'')+' data-act="reserve">Reserve a place</button><button data-act="details">View details</button></div>';}
if(k==='density'){h='<h3>Your workshops</h3>'+['Creative writing','Photography','Printmaking'].map((t,i)=>'<div style="padding:'+s.padding+'px 0;text-align:'+s.align.toLowerCase()+';border-bottom:'+(s.lines?'1px solid #dce1eb':'0')+'"><strong>'+t+'</strong><p class="small" style="margin:4px 0">Saturday · '+(10+i)+':00 AM</p><button data-act="details">View details</button></div>').join('');}
if(k==='ux'){let step=actionState.step||0;h=step===0?card():step===1?'<h3>Review your reservation</h3><p>Creative writing · Saturday, 10:00 AM</p><div class="row"><button data-act="back">Back</button><button class="primary" data-act="complete">Confirm reservation</button></div>':'<h3>You’re booked.</h3><p class="message" role="status">Your place in Creative writing is reserved.</p><button data-act="restart">Try again</button>';extra='<div class="legend">Actions taken: '+(actionState.clicks||0)+'</div>';}
if(k==='ia'){let labels=s.clear?['Workshops','Reservations','Account']:['Discover','My space','More'];let tab=actionState.tab??0;h='<div class="row" style="margin-bottom:24px">'+labels.map((t,i)=>'<button data-act="tab" data-tab="'+i+'" '+(tab===i?'class="primary" aria-pressed="true"':'aria-pressed="false"')+'>'+t+'</button>').join('')+'</div>'+['<h3>Upcoming workshops</h3>'+tiles(1),'<h3>Your reservations</h3><p>You have no reservations yet.</p>','<h3>Your account</h3><p>Manage your contact information.</p>'][tab];}
if(k==='content'){h='<h3>'+(s.specific?'Reserve your workshop':'Almost there')+'</h3><label for="content-name">'+(s.specific?'Your name':'Enter information')+'</label><input id="content-name" value="'+esc(actionState.name||'')+'"><button class="primary" style="margin-top:16px" data-act="submit">'+esc(s.specific?s.button:'Continue')+'</button>'+(actionState.error?'<p class="message error" role="alert">'+(s.specific?'Enter your name so we can identify your reservation.':'Something went wrong.')+'</p>':'');}
if(k==='controls'){h='<h3>Creative writing</h3><p>Saturday · 10:00 AM</p><button data-act="reserve" '+(s.recognizable?'class="primary"':'style="border:0;background:transparent;padding:0;color:inherit"')+'>'+(s.label?'Reserve a place':'Go')+'</button>';}
if(k==='status'){h='<h3>Workshop notes</h3><p>Bring a notebook and one idea you would like to explore.</p><button class="primary" data-act="save" '+(actionState.busy?'disabled':'')+'>Save notes</button>'+(s.feedback&&actionState.busy?'<div class="progress"><div style="width:65%"></div></div><p role="status">Saving your notes…</p>':'')+(s.feedback&&actionState.saved?'<p class="message" role="status">Your notes are saved.</p>':'');}
if(k==='prevention'){h=actionState.deleted?'<h3>Project deleted</h3><p>The sample project has been removed.</p><button data-act="restart">Restore example</button>':'<h3>Weekend workshop</h3><p>A sample project with three workshop plans.</p><button data-act="delete">Delete project</button>'+(actionState.confirm?'<section class="legend" role="region" aria-label="Deletion confirmation"><strong>Delete Weekend workshop?</strong><p>This removes the sample project.</p><div class="row"><button data-act="cancel-delete">Keep project</button><button data-act="confirm-delete">Delete project</button></div></section>':'');}
if(k==='recovery'){h='<h3>Your tasks</h3>'+(actionState.deleted?'<p class="small">No tasks remaining.</p>':'<div class="tile"><strong>Prepare workshop notes</strong><p class="small">Due Friday</p><button data-act="remove">Remove task</button></div>')+(actionState.deleted&&s.undo?'<div class="message" role="status">Task removed. <button data-act="undo">Undo removal</button></div>':'');}
if(k==='access'){style='';h='<div class="focus-demo '+(!s.focus?'no-focus':'')+'"><h3>Reserve a place</h3><label for="accessible-name">Your name</label><input id="accessible-name"><label for="accessible-email">Email address</label><input id="accessible-email" type="email"><button class="primary" style="margin-top:18px;min-height:'+s.target+'px" data-act="reserve">Reserve a place</button></div>';}
if(k==='responsive'){style='max-width:'+s.width+'px;width:100%';let cols=s.adapt?(s.width<400?1:2):3;h='<h3>Weekend workshops</h3><div class="samplegrid" style="grid-template-columns:repeat('+cols+',minmax(0,1fr))">'+tiles()+'</div>';extra='<div class="legend">Requested width: '+s.width+'px. The preview is also limited by your available screen space.</div>';}
if(k==='system'){h='<h3>Pick your next workshop</h3><div class="samplegrid">'+['Creative writing','Photography'].map((t,i)=>'<div class="tile" style="border-radius:'+(s.shared?s.radius:i?0:18)+'px"><strong>'+t+'</strong><p class="small">Saturday · '+(10+i)+':00 AM</p><button data-act="reserve" style="background:'+(s.shared?s.accent:i?'#b62452':'#2334ea')+';color:white;border:0;border-radius:'+(s.shared?s.radius:i?0:18)+'px;padding:'+(s.shared?'10px 16px':i?'5px 24px':'14px 10px')+'">Reserve a place</button></div>').join('')+'</div>';let r=ratio('#ffffff',s.accent);extra=s.shared?'<div class="legend">White text on accent: '+r.toFixed(2)+':1 · '+(r>=4.5?'Passes':'Below')+' normal-text AA</div>':'';}
if(k==='usability'){let started=actionState.started;h='<h3>Practice task</h3><p>Reserve a place in the Creative writing workshop.</p>'+(actionState.finished?'<p class="message" role="status">Task completed in '+actionState.seconds+' seconds.</p><button data-act="restart">Try again</button>':!started?'<button class="primary" data-act="start-test">Start task</button>':'<div class="row"><button data-act="wrong">'+(s.clear?'Your account':'My space')+'</button><button data-act="find-workshop">'+(s.clear?'Workshops':'Discover')+'</button></div>'+(actionState.found?'<div class="tile" style="margin-top:16px"><strong>Creative writing</strong><p>Saturday · 10:00 AM</p><button class="primary" data-act="finish-test">Reserve a place</button></div>':'')+(actionState.wrong?'<p class="message">Your account details are here. Try another section to find a workshop.</p>':''));}
if(k==='heuristics'){h='<h3>Workshop project</h3>'+(!actionState.deleted?'<p>Three workshop plans are ready to save.</p><div class="row"><button class="primary" data-act="heuristic-save">'+(s.wording?'Save project':'Persist entity')+'</button><button data-act="remove">'+(s.wording?'Remove project':'Invalidate entity')+'</button></div>':'<p>Project removed.</p>')+(actionState.saved&&s.feedback?'<p class="message" role="status">Project saved.</p>':'')+(actionState.deleted&&s.undo?'<div class="message">Project removed. <button data-act="undo">Undo removal</button></div>':'')+'<p class="small" style="margin-top:22px"><a href="https://www.nngroup.com/articles/ten-usability-heuristics/" target="_blank" rel="noopener">Read Nielsen’s ten heuristics</a></p>';}
if(l.group==='Style & motion'){const result=renderStyleExample(k,s);h=result.h;style=result.style;extra=result.extra;}
if(k==='workshop'){const result=renderWorkshop(s);h=result.h;style=result.style;extra=result.extra;}
if(actionState.result)h+='<p class="message" role="status">'+esc(actionState.result)+'</p>';
renderViewport(h,style,extra,k,l.group);
}
$('controls').addEventListener('input',e=>{const key=e.target.dataset.key;if(!key)return;const c=lessons[current].controls.find(c=>c.key===key);state[key]=c.type==='checkbox'?e.target.checked:c.type==='range'?Number(e.target.value):e.target.value;if(key==='direction'&&lessons[current].kind==='workshop'){const p=presetByName(state.direction);state.brand=p.brand;state.spacing=p.space;state.radius=p.radius;state.layout='Preset default';state.headingFont='Preset default';state.fontScale=1;renderLesson();return;}if(c.type==='range')$('o-'+key).textContent=state[key]+c.unit;clearTimeout(timer);actionState={};renderPreview();});
function handlePreviewInput(e){if(e.target.id==='content-name')actionState.name=e.target.value;}
function handlePreviewClick(e){if(lessons[current].kind==='workshop'){selectWorkshopElement(e);return;}const b=e.target.closest('[data-act]');if(!b)return;const a=b.dataset.act,k=lessons[current].kind;if(styleAction(a,state))return;delete actionState.result;
if(a==='restart'){clearTimeout(timer);actionState={};}
if(a==='reserve'){if(k==='ux'){actionState.clicks=(actionState.clicks||0)+1;actionState.step=state.extra?1:2;}else actionState.result='Your place is reserved. This is a practice example.';}
if(a==='back'){actionState.step=0;actionState.clicks++;}if(a==='complete'){actionState.step=2;actionState.clicks++;}
if(a==='details')actionState.result='Bring a notebook. No prior experience is required.';
if(a==='tab')actionState.tab=Number(b.dataset.tab);
if(a==='submit'){actionState.name=previewElement('content-name').value;actionState.error=!actionState.name.trim();if(!actionState.error)actionState.result='Your place is reserved, '+actionState.name.trim()+'.';}
if(a==='save'){actionState.busy=true;actionState.saved=false;timer=setTimeout(()=>{actionState.busy=false;actionState.saved=true;renderPreview();},3000);}
if(a==='delete'){if(state.confirm)actionState.confirm=true;else actionState.deleted=true;}if(a==='cancel-delete')actionState.confirm=false;if(a==='confirm-delete'){actionState.deleted=true;actionState.confirm=false;}
if(a==='remove')actionState.deleted=true;if(a==='undo')actionState.deleted=false;if(a==='heuristic-save')actionState.saved=true;
if(a==='start-test'){actionState.started=Date.now();}if(a==='wrong')actionState.wrong=true;if(a==='find-workshop')actionState.found=true;if(a==='finish-test'){actionState.finished=true;actionState.seconds=((Date.now()-actionState.started)/1000).toFixed(1);}
renderPreview();const target=a==='delete'&&actionState.confirm?'[data-act="cancel-delete"]':a==='remove'&&state.undo?'[data-act="undo"]':a==='undo'?'[data-act="remove"]':a==='tab'?'[data-tab="'+b.dataset.tab+'"]':a==='start-test'?'[data-act="find-workshop"]':a==='find-workshop'?'[data-act="finish-test"]':a==='submit'?'#content-name':a==='reserve'&&k==='ux'?(actionState.step===1?'[data-act="complete"]':'[data-act="restart"]'):a==='complete'?'[data-act="restart"]':a==='confirm-delete'?'[data-act="restart"]':a==='cancel-delete'?'[data-act="delete"]':'[data-act="'+a+'"]';if(target)previewFocus=target;}
let last='';$('topics').innerHTML=lessons.map((l,i)=>{let group=l.group!==last?'<div class="group">'+l.group+'</div>':'';last=l.group;return group+'<button data-lesson="'+i+'" aria-current="false"><span>'+String(i+1).padStart(2,'0')+'</span>'+l.title+'</button>';}).join('');
$('topics').addEventListener('click',e=>{const b=e.target.closest('[data-lesson]');if(b)initialize(Number(b.dataset.lesson));});$('reset').onclick=()=>{if(lessons[current].kind==='workshop'){elementOverrides={};selectedElement=null;}initialize(current);};$('previous').onclick=()=>initialize(Math.max(0,current-1));$('next').onclick=()=>initialize(Math.min(lessons.length-1,current+1));initialize(0);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_design_principle',description:'Open a design principle and reset its live example.',inputSchema:{type:'object',properties:{principle:{type:'string',enum:lessons.map(l=>l.title)}},required:['principle'],additionalProperties:false},execute(input){const index=lessons.findIndex(l=>l.title===input.principle);if(index<0)throw Error('Unknown principle');initialize(index);return{principle:lessons[current].title,controls:state};}})).catch(()=>{});}catch{}}

