/* A separate, original component collection for later theme assembly. */
const benchVariants={Buttons:['Lift','Fade','Outline fill'], 'Hamburger menus':['Cross','Collapse','Rotate'],Parallax:['Gentle','Deep']};
let benchVariant='',benchName='',benchReplayPending=false;
function createComponentBenchLesson(){return {group:'Build a theme',title:'Component playground',kind:'componentBench',description:'Build reusable pieces independently of a page. Try a variation, adjust its settings, save it to your collection, or export its working code. Start with buttons, hamburger animations, and parallax. We will grow this library with components recreated from website and CodePen examples.',challenge:'Choose a category and variation. Try keyboard focus and all three device widths, then save a named component.',notice:'This collection is separate from Theme Workshop’s section selector. Exported components use shared CSS variables so they can adopt a theme later. New examples are added to the library as reusable variations.',controls:[select('benchCategory','Category',Object.keys(benchVariants),'Buttons'),color('benchBrand','Accent','#853224'),range('benchRadius','Corners',0,40,8,'px'),range('benchDuration','Duration',0,1500,250,'ms',50),select('benchEasing','Easing',motionEasings,'ease-in-out')]};}
function currentBenchVariant(){const options=benchVariants[state.benchCategory];return options.includes(benchVariant)?benchVariant:options[0];}
function benchConfig(){return {schemaVersion:1,name:benchName.trim()||state.benchCategory+' / '+currentBenchVariant(),category:state.benchCategory,variant:currentBenchVariant(),settings:{...state},tokens:['--dl-brand','--dl-on-brand','--dl-radius','--dl-duration','--dl-easing'],integration:'Load component.css and component-runtime.js. Set shared --dl-* variables on the containing theme. Use unique IDs when duplicating menu fragments.'};}
function benchMarkup(c){const variant=c.variant.toLowerCase().replaceAll(' ','-');if(c.category==='Buttons')return '<section class="bench-component"><h2>Make the next move.</h2><p>Hover, tap, or tab to the button.</p><button class="bench-button bench-'+variant+'" type="button">Explore something new</button><p class="bench-status" role="status"></p></section>';
if(c.category==='Hamburger menus')return '<header class="bench-component bench-menu bench-'+variant+'"><div class="bench-menu-row"><a class="bench-logo" href="#bench-content">Your brand</a><button class="bench-toggle" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="bench-navigation"><span></span><span></span><span></span></button></div><nav id="bench-navigation" aria-label="Main navigation" hidden><a href="#bench-content">Explore</a><a href="#bench-content">About</a><a href="#bench-content">Contact</a></nav><div id="bench-content"><h2>A menu with character.</h2><p>Open it, then try Escape or the same toggle to close it.</p></div></header>';
return '<section class="bench-component"><h2>A little depth.</h2><p>Scroll inside this scene. Reduced motion keeps the image still.</p><div class="bench-parallax" tabindex="0" aria-label="Scrollable parallax example" data-speed="'+(c.variant==='Deep'?.3:.12)+'"><div class="bench-scene"><img src="coast.jpg" alt="Red lighthouse on a rocky coast at sunset."><div class="bench-parallax-copy"><h3>Follow the coast.</h3><p>Move at your own pace.</p></div></div><div class="bench-after"><h3>Room for the next chapter.</h3><p>The foreground and photograph move at different speeds.</p></div></div></section>';}
function benchTokenCSS(c){const s=c.settings;return '.bench-theme{--dl-brand:'+s.benchBrand+';--dl-on-brand:'+bestOnColor(s.benchBrand)+';--dl-radius:'+s.benchRadius+'px;--dl-duration:'+s.benchDuration+'ms;--dl-easing:'+s.benchEasing+';}';}
function renderComponentBench(){const c=benchConfig();return {h:'<style>'+benchTokenCSS(c)+'</style><div class="bench-theme">'+benchMarkup(c)+'</div>',style:'width:100%;max-width:1000px',extra:''};}
function readBenchCollection(){try{const items=JSON.parse(localStorage.getItem('design-lab-components-v1')||'[]');return Array.isArray(items)?items.filter(validBenchConfig).slice(0,50).map(({source,...item})=>item):[];}catch{return [];}}
function validBenchConfig(c){return c&&typeof c.name==='string'&&c.name.length<=100&&benchVariants[c.category]?.includes(c.variant)&&/^#[0-9a-f]{6}$/i.test(c.settings?.benchBrand)&&Number.isFinite(c.settings.benchRadius)&&c.settings.benchRadius>=0&&c.settings.benchRadius<=40&&Number.isFinite(c.settings.benchDuration)&&c.settings.benchDuration>=0&&c.settings.benchDuration<=1500&&motionEasings.includes(c.settings.benchEasing)&&c.settings.benchCategory===c.category;}
function showComponentBenchTools(kind){let box=document.getElementById('bench-tools');if(!box){box=document.createElement('section');box.id='bench-tools';box.className='bench-tools';document.querySelector('.controls .prompt').before(box);}box.hidden=kind!=='componentBench';if(box.hidden)return;for(const key of ['benchBrand','benchDuration','benchEasing'])document.getElementById('c-'+key).closest('.control').hidden=state.benchCategory==='Parallax';box.innerHTML='<h3>Reusable components</h3><label>Variation<select id="bench-variant">'+benchVariants[state.benchCategory].map(v=>'<option '+(v===currentBenchVariant()?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Component name<input id="bench-name" maxlength="100" value="'+esc(benchName)+'" placeholder="My coastal button"></label><p class="export-note">For buttons, easing and duration changes replay the effect. Replay effect lets you compare it again; hover or tab to test it yourself.</p><button id="bench-replay">Replay effect</button><button id="bench-save">Save to collection</button> <button id="bench-export">Export component ZIP</button><p id="bench-status" role="status"></p><h3>My collection</h3><div id="bench-collection"></div><p class="export-note">Collection saves live on this device. Export a ZIP for a portable copy. Adding saved variations directly into Theme Workshop is the next integration step.</p>';
box.querySelector('#bench-variant').onchange=e=>{benchVariant=e.target.value;benchReplayPending=true;renderPreview();};box.querySelector('#bench-name').oninput=e=>benchName=e.target.value;box.querySelector('#bench-replay').hidden=state.benchCategory!=='Buttons';box.querySelector('#bench-replay').onclick=()=>replayBenchEffect(previewDocument());
box.querySelector('#bench-save').onclick=()=>{const c=benchConfig();try{const items=readBenchCollection();if(items.length>=50)throw Error('Collection is full. Export or remove a saved item first.');c.id=crypto.randomUUID();items.push(c);localStorage.setItem('design-lab-components-v1',JSON.stringify(items));renderBenchCollection();box.querySelector('#bench-status').textContent='Saved '+c.name+'.';}catch(e){box.querySelector('#bench-status').textContent=e.message==='Collection is full. Export or remove a saved item first.'?e.message:'Saving is unavailable; export a ZIP instead.';}};
box.querySelector('#bench-export').onclick=()=>exportBenchComponent(benchConfig());renderBenchCollection();}
function renderBenchCollection(){const box=document.getElementById('bench-collection'),items=readBenchCollection();box.innerHTML=items.length?items.map((c,i)=>'<article class="bench-saved"><strong>'+esc(c.name)+'</strong><p class="export-note">'+esc(c.category+' · '+c.variant)+'</p><button data-bench-load="'+i+'">Load</button><button data-bench-export="'+i+'">Export</button><button data-bench-delete="'+i+'">Remove</button></article>').join(''):'<p class="export-note">No saved components yet.</p>';box.onclick=e=>{const b=e.target.closest('button');if(!b)return;const i=Number(b.dataset.benchLoad??b.dataset.benchExport??b.dataset.benchDelete),c=items[i];if(!c)return;if(b.hasAttribute('data-bench-load')){state={...c.settings};benchVariant=c.variant;benchName=c.name;renderLesson();}else if(b.hasAttribute('data-bench-export'))exportBenchComponent(c);else {try{items.splice(i,1);localStorage.setItem('design-lab-components-v1',JSON.stringify(items));renderBenchCollection();document.getElementById('bench-status').textContent='Removed '+c.name+'.';}catch{document.getElementById('bench-status').textContent='Could not update this device’s collection.';}}};}
async function exportBenchComponent(c){const status=document.getElementById('bench-status');status.textContent='Preparing component…';try{const responses=await Promise.all(['component-bench.css','component-bench-runtime.js','coast.jpg'].map(p=>fetch(p)));if(responses.some(r=>!r.ok))throw Error();const files={'component.html':benchMarkup(c),'component.css':benchTokenCSS(c)+'\n'+await responses[0].text(),'component-runtime.js':await responses[1].text(),'component.json':JSON.stringify(c,null,2),'README.md':'# '+c.name+'\n\n'+c.integration+'\n\nRun python3 -m http.server 8000 and open http://localhost:8000. Replace sample assets and connect button/link actions. Reduced motion disables animation.\n','index.html':'<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(c.name)+'</title><link rel="stylesheet" href="component.css"><script src="component-runtime.js" defer></script></head><body><main class="bench-theme">'+benchMarkup(c)+'</main></body></html>'};if(c.category==='Parallax')files['coast.jpg']=new Uint8Array(await responses[2].arrayBuffer());const url=URL.createObjectURL(makeComponentZip(files)),a=document.createElement('a');a.href=url;a.download='design-lab-'+c.category.toLowerCase().replaceAll(' ','-')+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Component exported with settings and code.';}catch{status.textContent='Export failed. Try again when the component files are available.';}}
