/* Course authoring is separate from Theme Workshop and the component collection. */
function sampleLmsCourse(){const section=(title,children)=>({id:LMS.uid(),type:'section',title,children}),slides=(title,items)=>({id:LMS.uid(),type:'slides',title,slides:items.map(([title,body])=>({id:LMS.uid(),title,body}))}),question=(prompt,options,answer,explanation)=>({id:LMS.uid(),prompt,options,answer,explanation}),quiz=(title,questions)=>({id:LMS.uid(),type:'quiz',title,questions});return {schemaVersion:1,id:LMS.uid(),title:'Design foundations',description:'A small course about making interfaces clear, usable and inclusive. Replace the sample material with your own.',settings:{passScore:80,allowRetakes:true,sequential:false,requireLessons:true,brand:'#285749',radius:12,font:'system'},sections:[section('01 · Start here',[slides('Welcome to the course',[['A place to learn','Learn at your own pace. Each section can contain more sections, slide decks, videos and quizzes. Your progress saves in this browser.'],['How to use this course','Use the outline to choose a lesson. Review each slide and mark lessons complete. The final quiz unlocks when the lessons are complete.']])]),section('02 · Design in practice',[section('Clarity and feedback',[slides('Make the next action clear',[['Say what happens next','“Save changes” tells people more than “Continue”. A label should describe the action and its outcome.'],['Make status visible','After someone saves, show a clear confirmation. If something fails, explain how they can recover.']]),{id:LMS.uid(),type:'video',title:'A short motion study',url:'motion.mp4',captions:'',description:'Silent abstract sample loop. Use the transcript below as its text alternative.',transcript:'A silent six-second abstract loop shows soft bands and shapes moving across a dark background. It demonstrates a decorative motion asset, rather than teaching through spoken narration.'},quiz('Check your understanding',[question('Which button label describes its action most clearly?',['Continue','Save changes','Next'],1,'Describe the action so people can predict its result.')])])])],finalQuiz:quiz('Final quiz',[question('What should a successful save show?',['No change','A clear confirmation','A new color only'],1,'Visible status tells the learner that their action succeeded.'),question('What helps people learn from video without hearing its audio?',['Autoplay','Captions and a transcript','A smaller video'],1,'Provide captions for synchronized audio and a transcript as a text alternative.')])};}
let lmsCourse=null,lmsSelected='',lmsPanel='structure',lmsSaveNote='',lmsSession=null,lmsWorkshopTheme=null;
const lmsAssets=new Map();let lmsMediaUrls=[];
function ensureLmsCourse(){if(lmsCourse)return;try{const stored=localStorage.getItem('design-lab-lms-draft-v1');lmsCourse=stored?LMS.validate(JSON.parse(stored)):sampleLmsCourse();}catch{lmsCourse=sampleLmsCourse();lmsSaveNote='The saved draft could not load. A sample course was opened.';}lmsSelected=lmsCourse.sections[0]?.id||lmsCourse.finalQuiz.id;persistLms();}
function createLmsLesson(){return {group:'Build a theme',title:'Learning management system',kind:'lms',description:'Create and export a course with nested sections, slide decks, videos, quizzes and browser-based reports.',challenge:'Build a section, test it at each device width, then export the working course.',notice:'The standalone course stores progress in each learner’s browser. Shared reporting, accounts and verified assessments need a backend.',controls:[]};}
function lmsNodes(nodes=lmsCourse.sections,parent=null){return nodes.flatMap(n=>[{node:n,parent,list:nodes},...(n.type==='section'?lmsNodes(n.children,n):[])]);}
function lmsFind(id){if(id===lmsCourse.finalQuiz.id)return {node:lmsCourse.finalQuiz,parent:null,list:null};return lmsNodes().find(x=>x.node.id===id);}
function lmsSelectedParent(){const entry=lmsFind(lmsSelected);return entry?.node.type==='section'?entry.node:entry?.parent;}
function persistLms(){try{localStorage.setItem('design-lab-lms-draft-v1',JSON.stringify(lmsCourse));lmsSaveNote='Draft saved on this device.';}catch{lmsSaveNote='Device saving is unavailable. Export your course to keep a copy.';}}
function renderLmsPreview(){ensureLmsCourse();return {h:'<div id="lms-root"></div>',style:'',extra:''};}
function mountLmsPreview(doc){lmsSession?.dispose();for(const url of lmsMediaUrls)URL.revokeObjectURL(url);lmsMediaUrls=[];const urls=new Map();for(const [path,bytes] of lmsAssets){const url=URL.createObjectURL(new Blob([bytes],{type:path.endsWith('.vtt')?'text/vtt':path.endsWith('.webm')?'video/webm':'video/mp4'}));urls.set(path,url);lmsMediaUrls.push(url);}let storage;try{storage=localStorage;}catch{}lmsSession=LMS.mount(doc,lmsCourse,{storage,timerHost:window,resolveMedia:path=>urls.get(path)});}
function showLmsTools(kind){let box=document.getElementById('lms-builder-tools');if(!box){box=document.createElement('section');box.id='lms-builder-tools';box.className='lms-builder-tools';document.querySelector('.controls .prompt').before(box);}box.hidden=kind!=='lms';if(box.hidden){lmsSession?.dispose();lmsSession=null;return;}ensureLmsCourse();renderLmsTools();}
function lmsRefresh(){persistLms();renderPreview();}
function renderLmsTools(){const box=document.getElementById('lms-builder-tools');box.innerHTML='<div class="lms-builder-tabs" role="group" aria-label="Course builder panel">'+[['structure','Structure'],['content','Content'],['settings','Settings'],['export','Export']].map(([key,title])=>'<button data-lms-panel="'+key+'" aria-pressed="'+(lmsPanel===key)+'">'+title+'</button>').join('')+'</div><div id="lms-builder-panel"></div><p id="lms-author-status" role="status">'+esc(lmsSaveNote)+'</p>';box.querySelectorAll('[data-lms-panel]').forEach(b=>b.onclick=()=>{lmsPanel=b.dataset.lmsPanel;renderLmsTools();});const panel=box.querySelector('#lms-builder-panel');
if(lmsPanel==='structure'){
 const tree=nodes=>nodes.map(n=>'<li><button data-lms-select="'+n.id+'" aria-current="'+(lmsSelected===n.id)+'">'+esc(n.title)+' <small>· '+esc(n.type)+'</small></button>'+(n.type==='section'?'<ul>'+tree(n.children)+'</ul>':'')+'</li>').join('');
 panel.innerHTML='<h3>Course structure</h3><p class="export-note">Select a section to add inside it. Select a lesson to add beside it. There is no fixed count of sections, subsections or lessons.</p><div class="lms-builder-actions"><button id="lms-add-root">+ Top-level section</button><button data-lms-add="section">+ Subsection</button><button data-lms-add="slides">+ Slides</button><button data-lms-add="video">+ Video</button><button data-lms-add="quiz">+ Quiz</button></div><ul class="lms-builder-tree">'+tree(lmsCourse.sections)+'<li><button data-lms-select="'+lmsCourse.finalQuiz.id+'" aria-current="'+(lmsSelected===lmsCourse.finalQuiz.id)+'">Final quiz · '+esc(lmsCourse.finalQuiz.title)+'</button></li></ul><p class="export-note">Selected: '+esc(lmsFind(lmsSelected)?.node.title||'None')+'</p><button id="lms-edit-selected">Edit selected content</button><div class="lms-builder-actions"><button data-lms-move="-1">Move up</button><button data-lms-move="1">Move down</button><button id="lms-delete-item" class="lms-danger">Remove selected</button></div>';
 panel.querySelectorAll('[data-lms-select]').forEach(b=>b.onclick=()=>{lmsSelected=b.dataset.lmsSelect;renderLmsTools();});panel.querySelector('#lms-edit-selected').onclick=()=>{lmsPanel='content';renderLmsTools();};
 const add=(type,root=false)=>{const parent=root?null:lmsSelectedParent();const n={id:LMS.uid(),type,title:type==='section'?'New section':type==='slides'?'New slide deck':type==='video'?'New video':'New quiz'};if(type==='section')n.children=[];if(type==='slides')n.slides=[{id:LMS.uid(),title:'First slide',body:'Add your learning material here.'}];if(type==='video')Object.assign(n,{url:'',captions:'',transcript:'',description:''});if(type==='quiz')n.questions=[{id:LMS.uid(),prompt:'Write your question',options:['First answer','Second answer'],answer:0,explanation:''}];(parent?.children||lmsCourse.sections).push(n);lmsSelected=n.id;lmsRefresh();};
 panel.querySelector('#lms-add-root').onclick=()=>add('section',true);panel.querySelectorAll('[data-lms-add]').forEach(b=>b.onclick=()=>add(b.dataset.lmsAdd));
 const entry=lmsFind(lmsSelected);panel.querySelectorAll('[data-lms-move]').forEach(b=>{const i=entry?.list?.indexOf(entry.node),j=i+Number(b.dataset.lmsMove);b.disabled=!entry?.list||j<0||j>=entry.list.length;b.onclick=()=>{[entry.list[i],entry.list[j]]=[entry.list[j],entry.list[i]];lmsRefresh();};});panel.querySelector('#lms-delete-item').disabled=!entry?.list;panel.querySelector('#lms-delete-item').onclick=()=>{if(!confirm('Remove '+entry.node.title+' and its contents?'))return;entry.list.splice(entry.list.indexOf(entry.node),1);lmsSelected=entry.parent?.id||lmsCourse.sections[0]?.id||lmsCourse.finalQuiz.id;lmsRefresh();};
}else if(lmsPanel==='content')renderLmsContent(panel);
else if(lmsPanel==='settings'){
 panel.innerHTML='<h3>Course settings</h3><label>Course title<input id="lms-course-title" maxlength="200" value="'+esc(lmsCourse.title)+'"></label><label>Description<textarea id="lms-course-description">'+esc(lmsCourse.description)+'</textarea></label><label>Passing score (%)<input data-lms-setting="passScore" type="number" min="0" max="100" value="'+lmsCourse.settings.passScore+'"></label>'+[['allowRetakes','Allow quiz retakes'],['sequential','Complete lessons in order'],['requireLessons','Finish lessons before final quiz']].map(([key,label])=>'<label><span><input type="checkbox" data-lms-setting="'+key+'" '+(lmsCourse.settings[key]?'checked':'')+'> '+label+'</span></label>').join('')+'<label>Theme accent<input data-lms-setting="brand" type="color" value="'+lmsCourse.settings.brand+'"></label><label>Corner radius<input data-lms-setting="radius" type="number" min="0" max="32" value="'+lmsCourse.settings.radius+'"></label><label>Typography<select data-lms-setting="font"><option value="system" '+(lmsCourse.settings.font==='system'?'selected':'')+'>System sans</option><option value="serif" '+(lmsCourse.settings.font==='serif'?'selected':'')+'>Serif</option></select></label><button id="lms-use-theme">Use Theme Workshop styles</button><p class="export-note">Copies the Workshop primary brand and radius. Course controls remain readable across accent colors. Exported CSS exposes shared theme variables.</p><h3>Mobile & accessibility</h3><p class="export-note">Use the toolbar’s phone, tablet and desktop previews. The learner view includes keyboard controls, semantic sections, radio groups, focus feedback, progress labels, a mobile outline, transcripts and captions, and reduced motion. Add meaningful transcripts/captions to your own videos.</p>';
 panel.querySelector('#lms-course-title').oninput=e=>{lmsCourse.title=e.target.value;lmsLiveEdit();};panel.querySelector('#lms-course-description').oninput=e=>{lmsCourse.description=e.target.value;lmsLiveEdit();};panel.querySelectorAll('[data-lms-setting]').forEach(input=>input.oninput=e=>{if(!input.validity.valid||input.value==='')return;const key=input.dataset.lmsSetting;lmsCourse.settings[key]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;lmsLiveEdit();});panel.querySelector('#lms-use-theme').onclick=()=>{const t=lmsWorkshopTheme||themeFromState(Object.fromEntries(createWorkshopLesson().controls.map(c=>[c.key,c.value])));lmsCourse.settings.brand=t.tokens.brand;lmsCourse.settings.radius=t.tokens.radius;lmsRefresh();};
}else{
 const issues=LMS.ready(lmsCourse),videos=LMS.flatten(lmsCourse.sections).filter(n=>n.type==='video'),missing=videos.filter(n=>n.url.startsWith('assets/')&&!lmsAssets.has(n.url)||n.captions.startsWith('assets/')&&!lmsAssets.has(n.captions));
 panel.innerHTML='<h3>Export your LMS</h3><p class="export-note">Working learner website + course.json + shared styles + runtime + Cursor handoff. Serve the folder locally or host it as a static website.</p>'+(issues.length?'<p>Course checks:</p><ul>'+issues.map(v=>'<li>'+esc(v)+'</li>').join('')+'</ul>':'<p>Lesson and quiz structure is ready.</p>')+(missing.length?'<p role="alert">Re-upload local assets for: '+missing.map(n=>esc(n.title)).join(', ')+'. File bytes are kept only for this authoring session.</p>':'')+'<button id="lms-export-zip" '+(issues.length||missing.length?'disabled':'')+'>Export course ZIP</button><button id="lms-export-json">Export course JSON</button><label>Import course JSON<input id="lms-import-json" type="file" accept="application/json,.json"></label><p class="export-note">The draft autosaves on this device. Course JSON preserves structure and settings; it does not contain uploaded video/caption bytes or learner progress. Keep the ZIP for a complete portable copy.</p><p class="export-note">Reports are local to a learner’s browser. This export does not provide accounts, cloud reporting or secure testing. The handoff describes how to add those services.</p>';
 panel.querySelector('#lms-export-zip').onclick=exportLms;panel.querySelector('#lms-export-json').onclick=()=>lmsDownload(new Blob([JSON.stringify(lmsCourse,null,2)],{type:'application/json'}),'course.json');panel.querySelector('#lms-import-json').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('Course JSON must be under 5 MB.');const next=LMS.validate(JSON.parse(await file.text()));if(!confirm('Replace the current course draft with '+next.title+'?'))return;lmsCourse=next;lmsSelected=next.sections[0]?.id||next.finalQuiz.id;lmsAssets.clear();lmsRefresh();}catch(error){document.getElementById('lms-author-status').textContent='Import failed: '+error.message;}};
}}
function lmsLiveEdit(){persistLms();document.getElementById('lms-author-status').textContent=lmsSaveNote;renderViewport('<div id="lms-root"></div>','','','lms','Build a theme');}
function renderLmsContent(panel){const entry=lmsFind(lmsSelected),n=entry?.node;if(!n){panel.innerHTML='<p>Select a course item in Structure first.</p>';return;}const input=(label,key,value,textarea=false)=>'<label>'+label+(textarea?'<textarea data-lms-field="'+key+'">'+esc(value)+'</textarea>':'<input data-lms-field="'+key+'" value="'+esc(value)+'" maxlength="'+(key==='title'?200:2000)+'">')+'</label>';
 panel.innerHTML='<h3>'+esc(n.type==='section'?'Section':n.type==='slides'?'Slide deck':n.type==='video'?'Video':'Quiz')+' content</h3>'+input('Title','title',n.title)+(entry.list?'<label>Parent section<select id="lms-parent"><option value="">Top level</option>'+lmsNodes().filter(x=>x.node.type==='section'&&x.node.id!==n.id&&!(n.type==='section'&&lmsNodes(n.children).some(y=>y.node.id===x.node.id))).map(x=>'<option value="'+x.node.id+'" '+(entry.parent?.id===x.node.id?'selected':'')+'>'+esc(x.node.title)+'</option>').join('')+'</select></label>':'')+(n.type==='section'?'<p class="export-note">Add slides, videos, quizzes or nested sections from Structure.</p>':'')+(n.type==='video'?input('Direct video URL or local filename','url',n.url)+input('Description','description',n.description,true)+input('Caption URL / WebVTT file','captions',n.captions)+input('Transcript / text alternative','transcript',n.transcript,true)+'<label>Upload video (MP4 / WebM, up to 50 MB)<input id="lms-upload-video" type="file" accept="video/mp4,video/webm,.mp4,.webm"></label><label>Upload captions (WebVTT)<input id="lms-upload-captions" type="file" accept="text/vtt,.vtt"></label><p class="export-note">YouTube watch links are not direct video files. Uploaded files are packaged in the ZIP; re-upload after refreshing the builder. Video playback is always learner-controlled.</p>':'');
 panel.querySelectorAll('[data-lms-field]').forEach(el=>el.oninput=()=>{const key=el.dataset.lmsField;if(['url','captions'].includes(key)&&el.value&&!LMS.mediaURL(el.value)){document.getElementById('lms-author-status').textContent='Use a direct HTTPS media URL or an MP4/WebM/VTT filename.';return;}n[key]=el.value;lmsLiveEdit();});
 panel.querySelector('#lms-parent')?.addEventListener('change',e=>{const parent=lmsFind(e.target.value)?.node;entry.list.splice(entry.list.indexOf(n),1);(parent?.children||lmsCourse.sections).push(n);lmsRefresh();});
 if(n.type==='video')for(const [key,selector,exts,max] of [['url','#lms-upload-video',['mp4','webm'],50],['captions','#lms-upload-captions',['vtt'],2]])panel.querySelector(selector).onchange=async e=>{const file=e.target.files[0];if(!file)return;const ext=file.name.split('.').at(-1).toLowerCase();if(!exts.includes(ext)||file.size>max*1024*1024){document.getElementById('lms-author-status').textContent='Choose an allowed file under '+max+' MB.';return;}const path='assets/'+n.id+'-'+(key==='url'?'video':'captions')+'.'+ext;lmsAssets.set(path,new Uint8Array(await file.arrayBuffer()));n[key]=path;lmsRefresh();};
 if(n.type==='slides'){
 const list=document.createElement('div');list.innerHTML=n.slides.map((s,i)=>'<article class="lms-builder-card"><h4>Slide '+(i+1)+'</h4><label>Heading<input data-slide="'+i+'" data-field="title" value="'+esc(s.title)+'"></label><label>Body<textarea data-slide="'+i+'" data-field="body">'+esc(s.body)+'</textarea></label><div class="lms-builder-actions"><button data-slide-move="'+i+'" data-step="-1" '+(i===0?'disabled':'')+'>Up</button><button data-slide-move="'+i+'" data-step="1" '+(i===n.slides.length-1?'disabled':'')+'>Down</button><button data-slide-remove="'+i+'">Remove slide</button></div></article>').join('')+'<button id="lms-add-slide">+ Add slide</button>';panel.append(list);list.querySelectorAll('[data-slide]').forEach(el=>el.oninput=()=>{n.slides[Number(el.dataset.slide)][el.dataset.field]=el.value;lmsLiveEdit();});list.querySelectorAll('[data-slide-move]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.slideMove),j=i+Number(b.dataset.step);[n.slides[i],n.slides[j]]=[n.slides[j],n.slides[i]];lmsRefresh();});list.querySelectorAll('[data-slide-remove]').forEach(b=>b.onclick=()=>{n.slides.splice(Number(b.dataset.slideRemove),1);lmsRefresh();});list.querySelector('#lms-add-slide').onclick=()=>{n.slides.push({id:LMS.uid(),title:'New slide',body:''});lmsRefresh();};
 }
 if(n.type==='quiz'){
 const list=document.createElement('div');list.innerHTML=n.questions.map((q,i)=>'<article class="lms-builder-card"><h4>Question '+(i+1)+'</h4><label>Question<textarea data-question="'+i+'" data-field="prompt">'+esc(q.prompt)+'</textarea></label>'+q.options.map((o,j)=>'<label>Choice '+(j+1)+'<input data-option-question="'+i+'" data-option="'+j+'" value="'+esc(o)+'"></label>').join('')+'<label>Correct answer<select data-question="'+i+'" data-field="answer">'+q.options.map((_,j)=>'<option value="'+j+'" '+(j===q.answer?'selected':'')+'>Choice '+(j+1)+'</option>').join('')+'</select></label><label>Feedback / explanation<textarea data-question="'+i+'" data-field="explanation">'+esc(q.explanation)+'</textarea></label><button data-add-choice="'+i+'">+ Choice</button><button data-remove-choice="'+i+'" '+(q.options.length<=2?'disabled':'')+'>Remove last choice</button><button data-remove-question="'+i+'">Remove question</button></article>').join('')+'<button id="lms-add-question">+ Add question</button>';panel.append(list);list.querySelectorAll('[data-question]').forEach(el=>el.oninput=()=>{n.questions[Number(el.dataset.question)][el.dataset.field]=el.dataset.field==='answer'?Number(el.value):el.value;lmsLiveEdit();});list.querySelectorAll('[data-option-question]').forEach(el=>el.oninput=()=>{n.questions[Number(el.dataset.optionQuestion)].options[Number(el.dataset.option)]=el.value;lmsLiveEdit();});list.querySelectorAll('[data-add-choice]').forEach(b=>b.onclick=()=>{n.questions[Number(b.dataset.addChoice)].options.push('New choice');lmsRefresh();});list.querySelectorAll('[data-remove-choice]').forEach(b=>b.onclick=()=>{const q=n.questions[Number(b.dataset.removeChoice)];q.options.pop();q.answer=Math.min(q.answer,q.options.length-1);lmsRefresh();});list.querySelectorAll('[data-remove-question]').forEach(b=>b.onclick=()=>{n.questions.splice(Number(b.dataset.removeQuestion),1);lmsRefresh();});list.querySelector('#lms-add-question').onclick=()=>{n.questions.push({id:LMS.uid(),prompt:'New question',options:['First answer','Second answer'],answer:0,explanation:''});lmsRefresh();};
 }
}
function lmsDownload(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function exportLms(){const status=document.getElementById('lms-author-status'),button=document.getElementById('lms-export-zip');button.disabled=true;status.textContent='Preparing your course…';try{const course=LMS.validate(lmsCourse);if(LMS.ready(course).length)throw Error('Finish the course checks before exporting.');const files={},responses=await Promise.all(['lms.css','lms-runtime.js'].map(p=>fetch(p)));if(responses.some(r=>!r.ok))throw Error('Course source files could not be loaded.');files['lms.css']=await responses[0].text();files['lms-runtime.js']=await responses[1].text();const videos=LMS.flatten(course.sections).filter(n=>n.type==='video');for(const n of videos)for(const path of [n.url,n.captions].filter(Boolean)){if(path.startsWith('assets/')){if(!lmsAssets.has(path))throw Error('Re-upload the local asset for '+n.title+'.');files[path]=lmsAssets.get(path);}else if(path==='motion.mp4'){const r=await fetch(path);if(!r.ok)throw Error('Sample video could not be loaded.');files[path]=new Uint8Array(await r.arrayBuffer());}else if(!/^https?:/.test(path)){throw Error('Upload the local media file for '+n.title+' before exporting.');}}
 files['course.json']=JSON.stringify(course,null,2);files['index.html']='<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(course.title)+'</title><link rel="stylesheet" href="lms.css"><script src="lms-runtime.js" defer></script></head><body class="lms-export-body"><div id="lms-root"></div><script id="lms-course-data" type="application/json">'+JSON.stringify(course).replaceAll('<','\\u003c')+'</script></body></html>';
 files['README.md']='# '+course.title+'\n\nRun `python3 -m http.server 8000` in this folder and open http://localhost:8000. You can deploy this directory to any static host. No install/build step is needed. Direct remote media URLs require connectivity and permission to load. Uploaded media is packaged in assets/.\n\nEdit course.json and copy its JSON into the lms-course-data script in index.html, or re-export from Design Lab. The embedded JSON lets the course load without a data API. Keep IDs stable to preserve progress; changing a lesson invalidates progress for that lesson.\n\nReports and learner settings are browser-local. No authentication, server, cloud dashboard, SCORM/xAPI integration or verified grading is included. Correct answers are in the client. Clearing browser data clears progress. Quiz attempts are not exam-secure.\n';
 files['CURSOR_HANDOFF.md']='# LMS integration handoff\n\nThis is a working static LMS generated by Design Lab. Keep learner markup and behavior from lms-runtime.js and use course.json as the course model. Sections can nest and contain slide decks, videos and multiple-choice quizzes. finalQuiz is separate. lms.css uses --lms-brand and --lms-radius; adapt those to shared website theme tokens.\n\nTest Learn, Reports, Settings, mobile outline, keyboard navigation, completion gates, retakes, captions/transcripts and browser persistence at 390/768/1440px. No video autoplays. Plain lesson text is escaped. Uploaded assets are local; external URLs stay external.\n\nFor shared reporting add users/enrollments, courses, lesson completions and quiz-attempt tables with an authenticated API. Grade on the server for trustworthy scores; never trust client completion/CSV. Add roles, access controls and a real instructor report before production multi-user use. Evaluate SCORM/xAPI only if needed by the target platform.\n';
 lmsDownload(makeComponentZip(files),'design-lab-lms.zip');status.textContent='Course ZIP exported with learner website, content and Cursor handoff.';}catch(e){status.textContent='Export failed: '+e.message;}finally{button.disabled=false;}}
