function createStyleLessons(){return [
{group:'Style & motion',title:'Color theory',description:'Color theory describes relationships between hues. Complementary colors sit opposite one another, analogous colors sit nearby, and monochromatic palettes vary one hue. These relationships can create cohesion or contrast, but readability depends on luminance too. Associations with color vary by context and culture.',challenge:'Keep the same hue and switch between palette relationships. Then reduce saturation and compare the feeling.',notice:'Notice which color attracts attention and whether the page feels unified. A harmonious palette can still have poor text contrast.',controls:[range('hue','Base hue',0,359,215,'°'),select('scheme','Palette relationship',['Complementary','Analogous','Monochromatic'],'Complementary'),range('saturation','Saturation',0,100,75,'%')],kind:'palette'},
{group:'Style & motion',title:'Image composition',description:'Image composition determines what people see and where their attention goes. Cropping, aspect ratio, and focal point can emphasize a subject or accidentally remove it. Choose images that support the content, and use alternative text when the image conveys meaningful information.',challenge:'Choose a square or portrait crop, then move the focal point until the lighthouse is visible.',notice:'The same photograph can feel entirely different when cropped. Check that the subject remains visible at every layout size.',controls:[select('aspect','Aspect ratio',['16:9','4:3','1:1','3:4'],'16:9'),range('x','Horizontal focal point',0,100,75,'%'),range('y','Vertical focal point',0,100,50,'%'),range('zoom','Image zoom',1,1.8,1,'×',.1)],kind:'image'},
{group:'Style & motion',title:'Overlapping layers',description:'Overlapping elements creates depth and can visually connect text to an image. Position, stacking order, and shadows determine what sits in front. Keep the reading order logical and avoid covering important parts of the image or making the layout break on small screens.',challenge:'Move the text card over the photo and switch its stacking order. Try a shadow to separate the layers.',notice:'Overlap should create a useful relationship. If essential words are hidden behind the image, the composition has failed even if it looks interesting.',controls:[range('overlap','Card overlap',0,110,50,'px'),select('front','Front layer',['Text card','Image'],'Text card'),range('shadow','Shadow strength',0,40,18,'px')],kind:'overlap'},
{group:'Style & motion',title:'Shapes & section dividers',description:'Section dividers change how one area flows into the next. Waves, angles, and curves can reinforce a visual identity or soften a transition. They are decorative structure; headings and spacing still need to explain where a new section begins.',challenge:'Compare a wave with an angled divider and vary the height. Watch how much space it consumes.',notice:'A divider should not clip text or create a confusing content boundary. Decorative shapes do not need screen-reader descriptions.',controls:[select('shape','Divider shape',['Wave','Angle','Curve','Straight'],'Wave'),range('depth','Divider height',0,100,45,'px'),color('sectionColor','Section color','#2334ea')],kind:'divider'},
{group:'Style & motion',title:'Background treatments',description:'Backgrounds can add atmosphere through images, gradients, and patterns. Their purpose is to support the foreground content. Overlays help separate text from busy imagery, while subtle patterns can add texture without competing with the message.',challenge:'Switch to an image background and lower the overlay. Then increase it until the text is comfortable to read.',notice:'Readability must hold across the entire area behind the words, not just one sampled pixel. Blur and darkness do different jobs.',controls:[select('treatment','Background',['Photo','Gradient','Dot pattern'],'Photo'),range('overlay','Dark overlay',0,85,45,'%'),range('blur','Background blur',0,12,0,'px'),color('base','Base color','#2334ea')],kind:'background'},
{group:'Style & motion',title:'Parallax',description:'Parallax creates depth by moving background and foreground layers at different rates as you scroll. It can make a scene feel more immersive, but strong motion can distract or cause discomfort. Essential information must remain available when motion is turned off.',challenge:'Scroll inside the example and increase the background movement. Compare it with reduced motion enabled.',notice:'Watch the image move relative to the text. Use small movement distances, preserve readability, and respect the person’s system motion preference.',controls:[range('strength','Movement strength',0,80,35,'px'),toggle('reduce','Reduce motion',false)],kind:'parallax'},
{group:'Style & motion',title:'Animation & transitions',description:'Animation shows a change over time; a transition connects two states. Duration determines speed, easing determines how speed changes, and distance affects how dramatic movement feels. Motion should explain state or guide attention rather than make people wait unnecessarily.',challenge:'Play the same entrance with different easing and duration settings. Compare fade, slide, and scale.',notice:'An animation should have a purpose and a usable final state. This example runs only when you press Play and respects reduced-motion preferences.',controls:[select('effect','Entrance effect',['Slide','Fade','Scale'],'Slide'),range('duration','Duration',100,1800,500,'ms',100),select('easing','Easing',['ease-out','linear','ease-in-out'],'ease-out'),toggle('reduce','Reduce motion',false)],kind:'animation'},
{group:'Style & motion',title:'Video backgrounds',description:'A video background adds movement behind foreground content. Treat purely atmospheric video as decorative, keep it silent, and provide an easy pause control. A poster image preserves the layout when video is stopped or unavailable; critical information should never exist only in the video.',challenge:'Play the background, change the overlay, and compare it with the still-image alternative.',notice:'Movement competes for attention. The locally hosted sample is a short abstract loop, not a recording of the coast. Your system’s reduced-motion setting keeps it still.',controls:[range('overlay','Dark overlay',0,85,45,'%'),toggle('still','Use still-image alternative',false)],kind:'video'},
{group:'Style & motion',title:'Art direction',description:'Art direction is the coherent combination of imagery, typography, color, composition, and motion. It gives a website a recognizable character. A consistent direction is stronger than adding unrelated effects simply because each one looks appealing.',challenge:'Switch styles while keeping the words and image unchanged. Notice how typography, layout, and color change the impression.',notice:'Compare the complete composition rather than one isolated color. A style should fit the audience and content while preserving readable text and recognizable controls.',controls:[select('direction','Visual direction',directionOptions(),'Editorial'),range('round','Image corners',0,36,8,'px')],kind:'direction'}
];}
const coast='coast.jpg';
function motionReduced(s){return s.reduce || (typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches);}
function renderStyleExample(k,s){
let h='',extra='',style='padding:0;overflow:hidden';
const image=(attrs='')=>'<img src="'+coast+'" alt="Red lighthouse above a rocky coastline at sunset." '+attrs+'>';
if(k==='palette'){let offsets=s.scheme==='Complementary'?[0,180,0]:s.scheme==='Analogous'?[-30,0,30]:[0,0,0];let colors=offsets.map((d,i)=>'hsl('+((s.hue+d+360)%360)+' '+s.saturation+'% '+(s.scheme==='Monochromatic'?[24,48,86][i]:[30,45,90][i])+'%)');h='<div class="palette-strips">'+colors.map(c=>'<div style="background:'+c+'"></div>').join('')+'</div><div class="style-copy" style="background:'+colors[2]+';color:#111827"><p class="style-kicker">COASTAL WEEKENDS</p><h3>Find a little perspective.</h3><p>A slower day by the sea.</p><button style="background:'+colors[0]+';color:white;border:0" data-act="details">Explore the coast</button></div>';extra='<div class="legend">'+s.scheme+' · Base hue '+s.hue+'°<br>Change the palette relationship, then check text contrast separately.</div>';}
if(k==='image'){let ar=s.aspect.replace(':',' / ');h='<div class="crop-frame" style="aspect-ratio:'+ar+';max-height:420px">'+image('style="object-position:'+s.x+'% '+s.y+'%;transform:scale('+s.zoom+');transform-origin:'+s.x+'% '+s.y+'%"')+'</div>';extra='<div class="legend">Focal point: '+s.x+'% across, '+s.y+'% down · '+s.aspect+'</div>';}
if(k==='overlap'){h='<div class="overlap-example">'+image('style="position:relative;z-index:'+(s.front==='Image'?3:1)+'"')+'<div class="overlap-card" style="position:relative;z-index:2;margin-top:-'+s.overlap+'px;box-shadow:0 '+s.shadow/2+'px '+s.shadow+'px #14234540"><p class="style-kicker">A WEEKEND AWAY</p><h3>Meet me by the water.</h3><p>Follow the coast. Leave a little room for discovery.</p></div></div>';}
if(k==='divider'){let path=s.shape==='Wave'?'M0 20 C150 100 350 -40 600 25 S850 100 1000 20 L1000 100 L0 100 Z':s.shape==='Angle'?'M0 0 L1000 90 L1000 100 L0 100 Z':s.shape==='Curve'?'M0 0 Q500 180 1000 0 L1000 100 L0 100 Z':'M0 0 H1000 V100 H0Z';h='<section class="divider-section" style="background:'+s.sectionColor+'"><div class="style-copy"><p class="style-kicker">COASTAL WEEKENDS</p><h3>Take the scenic route.</h3><p>Give your next idea room to breathe.</p></div><svg aria-hidden="true" viewBox="0 0 1000 100" preserveAspectRatio="none" style="height:'+s.depth+'px"><path d="'+path+'" fill="white"/></svg></section><div class="style-copy"><h3>Your next chapter</h3><p>A clear heading begins the next section.</p></div>';}
if(k==='background'){let bg=s.treatment==='Photo'?"url('"+coast+"')":s.treatment==='Gradient'?'linear-gradient(130deg,'+s.base+',#dc5389)':'radial-gradient(#ffffff55 2px,transparent 2px)';h='<div class="media-hero"><div class="hero-background" style="background-color:'+s.base+';background-image:'+bg+';background-size:'+(s.treatment==='Dot pattern'?'20px 20px':'cover')+';filter:blur('+s.blur+'px)"></div><div class="hero-shade" style="background:rgba(0,0,0,'+s.overlay/100+')"></div><div class="hero-copy"><p class="style-kicker">COASTAL WEEKENDS</p><h3>Find a little perspective.</h3><p>Slow down. Look around. Start something new.</p></div></div>';}
if(k==='parallax'){h='<div class="parallax-window" id="parallax-window" tabindex="0" aria-label="Scrollable parallax example"><div class="parallax-scene"><img id="parallax-image" src="'+coast+'" alt="" style="transform:translateY(0)"><div class="parallax-shade"></div><div class="parallax-copy"><p class="style-kicker">SCROLL INSIDE THIS EXAMPLE</p><h3>A different point of view.</h3><p>The words and image move at different rates.</p></div></div><div class="style-copy"><h3>Keep exploring.</h3><p>The content remains available when motion is off.</p><p>Scroll back up to compare the layers.</p></div></div>';extra='<div class="legend">'+(motionReduced(s)?'Reduced motion is active. The background stays still.':'Scroll inside the scene or focus it and use the arrow keys.')+'</div>';}
if(k==='animation'){h='<div class="style-copy"><button data-act="play-animation" class="primary">Play entrance</button><div class="animation-card" id="animated-card"><span class="pill">WEEKEND JOURNAL</span><h3>A fresh perspective.</h3><p>One image. One idea. One new beginning.</p></div></div>';extra='<div class="legend">'+(motionReduced(s)?'Reduced motion is active. The final state appears without animation.':s.effect+' · '+s.duration+'ms · '+s.easing)+'</div>';}
if(k==='video'){h='<div class="media-hero video-hero"><video id="background-video" muted loop playsinline preload="metadata" poster="motion-poster.jpg" aria-hidden="true"><source src="motion.mp4" type="video/mp4"></video><div class="hero-shade" style="background:rgba(0,0,0,'+s.overlay/100+')"></div><div class="hero-copy"><p class="style-kicker">ROOM TO CREATE</p><h3>Let an idea take shape.</h3><p>Keep your message clear while the background moves.</p></div></div><div class="style-copy video-controls"><button data-act="toggle-video" id="video-toggle" '+(s.still||motionReduced(s)?'disabled':'')+'>Play background</button><span id="video-status" role="status">'+(s.still?'Still-image alternative':motionReduced(s)?'System reduced motion: still image':'Background paused')+'</span></div>';extra='<div class="legend">A silent abstract video loop. Playback starts only when you choose Play.</div>';}
if(k==='direction'){const result=renderWorkshop(s,['hero']);h=result.h;style='padding:0';extra='<div class="legend">'+esc(presetByName(s.direction).character)+'<br>Open Theme workshop to customize, choose components, and export this direction.</div>';}
return {h,style,extra};}
function mountStyleExample(k,s){if(k==='parallax'){const area=previewElement('parallax-window'),image=previewElement('parallax-image');area?.addEventListener('scroll',()=>{if(image)image.style.transform='translateY('+(motionReduced(s)?0:Math.min(area.scrollTop/300,1)*s.strength)+'px)';},{passive:true});}}
function styleAction(a,s){
if(a==='play-animation'){const el=previewElement('animated-card');if(!el)return true;if(!motionReduced(s)&&el.animate){const from=s.effect==='Fade'?{opacity:0}:s.effect==='Scale'?{opacity:0,transform:'scale(.82)'}:{opacity:0,transform:'translateY(45px)'};el.animate([from,{opacity:1,transform:'none'}],{duration:s.duration,easing:s.easing});}return true;}
if(a==='toggle-video'){const video=previewElement('background-video'),button=previewElement('video-toggle'),status=previewElement('video-status');if(!video||s.still||motionReduced(s))return true;if(video.paused){video.play().then(()=>{button.textContent='Pause background';status.textContent='Background playing';}).catch(()=>{status.textContent='Playback unavailable. The still image is shown.';});}else{video.pause();button.textContent='Play background';status.textContent='Background paused';}return true;}
return false;
}

