/* Original preset interpretations: no external fonts or runtime dependencies. */
const designPresets=[
{name:'Editorial',family:'Modern',bg:'#f6f2ea',paper:'#ffffff',ink:'#252321',brand:'#853224',font:'Georgia, serif',body:'system-ui, sans-serif',radius:2,space:30,layout:'split',character:'Serif headlines, measured spacing, a strong reading rhythm.'},
{name:'Playful',family:'Modern',bg:'#fff1a8',paper:'#ffffff',ink:'#202052',brand:'#b11b61',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:24,space:24,layout:'split',character:'Rounded shapes, lively color, an offset image frame.'},
{name:'Minimal',family:'Modern',bg:'#ffffff',paper:'#f6f6f6',ink:'#181818',brand:'#282828',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:40,layout:'split',character:'Restrained typography, generous space, simple surfaces.'},
{name:'Dramatic',family:'Modern',bg:'#101827',paper:'#1e293b',ink:'#f8fafc',brand:'#ff946e',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:32,layout:'overlay',character:'Dark surfaces, oversized headings, an atmospheric image.'},
{name:'Material-inspired',family:'Modern',bg:'#f3f0fc',paper:'#ffffff',ink:'#251d36',brand:'#6342a6',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:24,space:24,layout:'split',character:'Rounded surfaces, clear emphasis, comfortable controls.'},
{name:'Glassmorphism',family:'Modern',bg:'#182343',paper:'#263352',ink:'#ffffff',brand:'#8fc9ff',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:20,space:28,layout:'overlay',character:'Translucent panels, subtle borders, layered backgrounds.'},
{name:'Luxury',family:'Modern',bg:'#141414',paper:'#24221d',ink:'#f6ecd5',brand:'#dfc181',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:40,layout:'split',character:'Fine borders, warm metallic accents, spacious serif type.'},
{name:'Nordic',family:'Modern',bg:'#eef3f2',paper:'#ffffff',ink:'#243635',brand:'#315e59',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:4,space:36,layout:'split',character:'Quiet surfaces, practical typography, natural colors.'},
{name:'Brutalist',family:'Experimental',bg:'#ffffff',paper:'#ffffff',ink:'#111111',brand:'#0000bb',font:'ui-monospace, monospace',body:'ui-monospace, monospace',radius:0,space:16,layout:'stack',character:'Exposed structure, obvious links, blunt typography.'},
{name:'Neo-brutalist',family:'Experimental',bg:'#faf1bd',paper:'#ffffff',ink:'#151515',brand:'#6742ba',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:24,layout:'split',character:'Thick outlines, hard shadows, assertive color blocks.'},
{name:'Collage',family:'Experimental',bg:'#f6dfcb',paper:'#fff9ed',ink:'#342a27',brand:'#9c3229',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:26,layout:'split',character:'Tilted imagery, layered captions, a cut-paper feeling.'},
{name:'Bauhaus',family:'Historical',bg:'#f6efdd',paper:'#fffdf4',ink:'#202126',brand:'#ba2727',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:28,layout:'split',character:'Geometric structure, primary-color accents, strong asymmetry.'},
{name:'Swiss International',family:'Historical',bg:'#ffffff',paper:'#f3f3f3',ink:'#171717',brand:'#bd2525',font:'Arial, Helvetica, sans-serif',body:'Arial, Helvetica, sans-serif',radius:0,space:32,layout:'split',character:'An orderly grid, left alignment, disciplined sans-serif type.'},
{name:'Art Deco',family:'Historical',bg:'#172a2e',paper:'#20363a',ink:'#f7edcf',brand:'#e5c775',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:32,layout:'stack',character:'Symmetry, fine geometric borders, a gold-accented palette.'},
{name:'Memphis',family:'Historical',bg:'#ffe7ec',paper:'#ffffff',ink:'#26214b',brand:'#68329f',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:8,space:24,layout:'split',character:'Bold outlines, contrasting pastels, patterned surfaces.'},
{name:'Early web',family:'Retro digital',bg:'#d6d6d6',paper:'#ffffff',ink:'#000000',brand:'#000099',font:'Times New Roman, serif',body:'Arial, sans-serif',radius:0,space:16,layout:'stack',character:'Beveled surfaces, underlined links, browser-era typography.'},
{name:'Terminal',family:'Retro digital',bg:'#07150b',paper:'#102119',ink:'#bef5c6',brand:'#77ed94',font:'ui-monospace, monospace',body:'ui-monospace, monospace',radius:0,space:20,layout:'stack',character:'Monospace type, green accents, explicit structural borders.'},
{name:'Y2K',family:'Retro digital',bg:'#e6edff',paper:'#ffffff',ink:'#162452',brand:'#244ec0',font:'Arial, sans-serif',body:'Arial, sans-serif',radius:18,space:24,layout:'split',character:'Glossy gradients, silver-blue surfaces, rounded capsules.'},
{name:'Synthwave',family:'Retro digital',bg:'#180b33',paper:'#281345',ink:'#fbedff',brand:'#ff92d0',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:4,space:28,layout:'overlay',character:'Neon accents, dark violet surfaces, a grid-like background.'},
{name:'Vaporwave',family:'Retro digital',bg:'#f4d5f3',paper:'#ffeefc',ink:'#462857',brand:'#702a91',font:'Georgia, serif',body:'ui-monospace, monospace',radius:2,space:28,layout:'split',character:'Pastel gradients, nostalgic serif type, tinted imagery.'}
];
let selectedComponents=['navigation','hero','cards','form','overlap'];
const componentLabels={navigation:'Navigation',hero:'Hero',cards:'Cards',form:'Form',overlap:'Image + text overlap',announcement:'Announcement bar',features:'Feature grid',gallery:'Image gallery',testimonials:'Testimonials',pricing:'Pricing cards',stats:'Statistics',faq:'FAQ',cta:'Call to action',footer:'Footer',slideshow:'Slideshow',lightbox:'Lightbox gallery'};
function presetByName(name){return designPresets.find(p=>p.name===name)||designPresets[0];}
function directionOptions(){return [...new Set(designPresets.map(p=>p.family))].map(f=>({label:f,items:designPresets.filter(p=>p.family===f).map(p=>p.name)}));}
function createWorkshopLesson(){return{group:'Build a theme',title:'Theme workshop',description:'Choose a visual direction, customize its shared settings, and test the same components at mobile, tablet, and desktop widths. Select the components you want and export their HTML, styles, assets, and a Cursor handoff. These are editable interpretations of design styles, not official standards.',challenge:'Choose a direction, inspect it at all three widths, then select only the components you want to export.',notice:'The export uses the same HTML and styles as this preview. Shared tokens guide new components; composition rules preserve the direction. Forms and calls to action are visual examples that need application behavior when integrated.',controls:[select('direction','Art direction',directionOptions(),'Editorial'),color('brand','Primary brand','#853224'),color('secondary','Secondary accent','#315e59'),color('background','Page background','#f6f2ea'),color('surface','Surface','#ffffff'),color('textColor','Text','#252321'),color('borderColor','Borders','#c7c3be'),select('headingFont','Heading font',['Preset default',...Object.keys(systemFaceStack)],'Preset default'),range('fontScale','Type scale',.8,1.4,1,'×',.05),range('spacing','Spacing',12,48,30,'px'),range('radius','Corners',0,32,2,'px'),select('layout','Hero arrangement',['Preset default','Split','Stack','Overlay'],'Preset default'),range('overlap','Image overlap',0,100,36,'px')],kind:'workshop'};}
function themeFromState(s){const p=presetByName(s.direction);const brand=s.brand||p.brand;return {schemaVersion:4,sharedButtonOverrides:JSON.parse(JSON.stringify(sharedButtonOverrides)),sectionSettings:JSON.parse(JSON.stringify(sectionSettings)),elementOverrides:JSON.parse(JSON.stringify(elementOverrides)),direction:p.name,family:p.family,character:p.character,tokens:{background:s.background||p.bg,surface:s.surface||p.paper,text:s.textColor||p.ink,secondary:s.secondary||'#315e59',border:s.borderColor||'#c7c3be',brand,onBrand:ratio('#ffffff',brand)>=ratio('#111111',brand)?'#ffffff':'#111111',headingFont:s.headingFont&&s.headingFont!=='Preset default'?(systemFaceStack[s.headingFont]||p.font):p.font,bodyFont:p.body,radius:Number(s.radius??s.round??p.radius),spacing:Number(s.spacing??p.space),fontScale:Number(s.fontScale??1)},composition:{hero:s.layout&&s.layout!=='Preset default'?s.layout.toLowerCase():p.layout,overlap:Number(s.overlap??36)},responsive:{mobileMax:599,tabletMax:999,desktopMin:1000},components:[...selectedComponents]};}
function themeVariables(t){const c=t.tokens;return '.dl-site{--dl-bg:'+c.background+';--dl-surface:'+c.surface+';--dl-text:'+c.text+';--dl-brand:'+c.brand+';--dl-on-brand:'+c.onBrand+';--dl-heading-font:'+c.headingFont+';--dl-body-font:'+c.bodyFont+';--dl-radius:'+c.radius+'px;--dl-space:'+c.spacing+'px;--dl-scale:'+c.fontScale+';--dl-overlap:'+t.composition.overlap+'px;--dl-secondary:'+c.secondary+';--dl-on-secondary:'+(ratio('#ffffff',c.secondary)>=ratio('#111111',c.secondary)?'#ffffff':'#111111')+';--dl-line:'+c.border+';}'+sectionSettingsCSS(t.sectionSettings)+sharedButtonCSS(t.sharedButtonOverrides)+elementOverrideCSS(t.elementOverrides);}
function componentMarkup(name,t){const img='<img src="coast.jpg" alt="Red lighthouse above a rocky coast at sunset." loading="lazy">';const names={navigation:'<header class="dl-nav"><a class="dl-logo" href="#dl-home">Coastal Weekends</a><nav aria-label="Main navigation"><a href="#dl-workshops">Workshops</a><a href="#dl-contact">Get in touch</a></nav></header>',hero:'<section id="dl-home" class="dl-hero dl-hero-'+t.composition.hero+'"><div class="dl-hero-copy"><p class="dl-kicker">MAKE ROOM FOR SOMETHING NEW</p><h1>Find a little perspective.</h1><p>A slower day by the sea. A little room for a new idea.</p><a class="dl-button" href="#dl-workshops">Explore workshops</a></div>'+img+'</section>',cards:'<section id="dl-workshops" class="dl-section"><h2>Choose your next chapter.</h2><div class="dl-grid">'+['Creative writing','Photography','Printmaking'].map((name,i)=>'<article class="dl-card"><p class="dl-kicker">WORKSHOP 0'+(i+1)+'</p><h3>'+name+'</h3><p>Explore a new skill at your own pace.</p><a href="#dl-contact">Ask about this workshop</a></article>').join('')+'</div></section>',form:'<section id="dl-contact" class="dl-section"><h2>Stay in the loop.</h2><form class="dl-form"><div><label for="dl-name">Your name</label><input id="dl-name" name="name" autocomplete="name" required></div><div><label for="dl-email">Email address</label><input id="dl-email" name="email" type="email" autocomplete="email" required></div><button class="dl-button" type="submit">Request information</button><p class="dl-form-note">Example form: connect submission behavior in your application.</p></form></section>',overlap:'<section class="dl-overlap dl-section">'+img+'<div class="dl-overlap-copy"><p class="dl-kicker">A DIFFERENT POINT OF VIEW</p><h2>Meet me by the water.</h2><p>Follow the coast. Leave room for discovery.</p></div></section>'};const template=document.createElement('template');const settings=layoutFor(name,t.sectionSettings);template.innerHTML=libraryMarkup(name,t,settings,names[name]||'');template.content.querySelectorAll('header,nav,section,article,div,a,h1,h2,h3,p,img,label,input,button,form,aside,footer,figure,figcaption,blockquote,details,summary,span').forEach((el,i)=>el.setAttribute('data-dl-element',name+'-'+i));return '<div class="dl-component dl-width-'+settings.width+' dl-height-'+settings.height+'" data-dl-component="'+name+'"><div class="dl-component-inner">'+template.innerHTML+'</div></div>';} 
function workshopMarkup(t,components=selectedComponents){return '<div class="dl-site dl-'+t.direction.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'">'+components.map(n=>componentMarkup(n,t)).join('')+'</div>';}
function renderWorkshop(s,components=selectedComponents){const t=themeFromState(s);return {h:'<style>'+themeVariables(t)+'</style>'+workshopMarkup(t,components),style:'',extra:''};}
function showWorkshopTools(kind,s){const box=document.getElementById('workshop-tools');box.hidden=kind!=='workshop';if(kind!=='workshop')return;document.querySelector('.controls').append(box);renderPaletteTools(s);const p=presetByName(s.direction);box.className='workshop-tools';box.innerHTML='<div class="style-summary"><strong>'+esc(p.family)+' · '+esc(p.name)+'</strong><p>'+esc(p.character)+'</p></div><fieldset style="border:0;padding:0;margin:0"><legend style="font-size:14px;font-weight:600">Component library — enable to preview and export</legend><div class="component-choices">'+Object.entries(componentLabels).map(([k,label])=>'<label><input type="checkbox" data-component="'+k+'" '+(selectedComponents.includes(k)?'checked':'')+'> '+label+'</label>').join('')+'</div></fieldset><div class="export-actions"><button id="export-theme" class="export-primary" '+(!selectedComponents.length?'disabled':'')+'>Export component ZIP</button><button id="save-theme">Save on this device</button><button id="load-theme">Load saved theme</button></div><p class="export-note">HTML components + shared CSS + theme.json + image + CURSOR_HANDOFF.md. These are portable source files, not screenshots.</p><p id="export-status" class="export-note" role="status"></p>';
box.querySelectorAll('[data-component]').forEach(c=>c.addEventListener('change',()=>{selectedComponents=Object.keys(componentLabels).filter(k=>box.querySelector('[data-component="'+k+'"]').checked);renderPreview();}));
box.querySelector('#export-theme').onclick=exportWorkshop;
box.querySelector('#save-theme').onclick=()=>{try{localStorage.setItem('design-lab-theme-v1',JSON.stringify({state,components:selectedComponents,elementOverrides,sectionSettings,sharedButtonOverrides}));document.getElementById('export-status').textContent='Theme saved on this device.';}catch{document.getElementById('export-status').textContent='Saving is unavailable in this browser. Export the ZIP instead.';}};
box.querySelector('#load-theme').onclick=()=>{try{const saved=JSON.parse(localStorage.getItem('design-lab-theme-v1'));if(!saved)throw Error('No saved theme');const lesson=lessons[current],next={};for(const c of lesson.controls){const v=saved.state?.[c.key];if(v===undefined&&['secondary','background','surface','textColor','borderColor'].includes(c.key)){next[c.key]=paletteDefaults(presetByName(saved.state?.direction))[c.key];continue;}if(c.type==='range'){if(typeof v!=='number'||!Number.isFinite(v)||v<c.min||v>c.max)throw Error('Invalid saved value');}else if(c.type==='color'){if(!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid color');}else if(c.type==='select'){const options=c.options.flatMap(o=>typeof o==='string'?[o]:o.items);if(!options.includes(v))throw Error('Invalid selection');}next[c.key]=v;}state=next;sharedButtonOverrides=validateButtonStyles(saved.sharedButtonOverrides);sectionSettings=validateSectionSettings(saved.sectionSettings);elementOverrides=validateElementOverrides(saved.elementOverrides);selectedElement=null;selectedComponents=Array.isArray(saved.components)?Object.keys(componentLabels).filter(k=>saved.components.includes(k)):Object.keys(componentLabels);renderLesson();document.getElementById('export-status').textContent='Saved theme loaded.';}catch{document.getElementById('export-status').textContent='No compatible saved theme on this device.';}};
}
/* Small, dependency-free ZIP writer using stored entries and CRC32. */
const zipCrcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function zipCrc(bytes){let n=0xffffffff;for(const b of bytes)n=zipCrcTable[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;}
function makeComponentZip(files){const enc=new TextEncoder(),chunks=[],central=[];let offset=0;for(const [path,value] of Object.entries(files)){const name=enc.encode(path),bytes=typeof value==='string'?enc.encode(value):value,crc=zipCrc(bytes);const local=new Uint8Array(30+name.length),lv=new DataView(local.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x0800,true);lv.setUint16(12,33,true);lv.setUint32(14,crc,true);lv.setUint32(18,bytes.length,true);lv.setUint32(22,bytes.length,true);lv.setUint16(26,name.length,true);local.set(name,30);chunks.push(local,bytes);const entry=new Uint8Array(46+name.length),ev=new DataView(entry.buffer);ev.setUint32(0,0x02014b50,true);ev.setUint16(4,20,true);ev.setUint16(6,20,true);ev.setUint16(8,0x0800,true);ev.setUint16(14,33,true);ev.setUint32(16,crc,true);ev.setUint32(20,bytes.length,true);ev.setUint32(24,bytes.length,true);ev.setUint16(28,name.length,true);ev.setUint32(42,offset,true);entry.set(name,46);central.push(entry);offset+=local.length+bytes.length;}
const length=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array(22),dv=new DataView(end.buffer);dv.setUint32(0,0x06054b50,true);dv.setUint16(8,central.length,true);dv.setUint16(10,central.length,true);dv.setUint32(12,length,true);dv.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
function exportHandoff(t){return '# Cursor handoff: '+t.direction+'\n\nUse this package as the visual source of truth for the website.\n\n## Files\n- index.html: assembled selected components, matching the Design Lab preview.\n- components/: separate HTML fragments.\n- theme.css: shared tokens and scoped component styles.\n- theme.json: palette, sectionSettings, elementOverrides, and sharedButtonOverrides.\n- coast.jpg: local sample image.\n- workshop-runtime.js: menu, slideshow, and lightbox behavior; include once per page.\n\n## Instructions\n1. Read these files before implementing the website. Preserve the selected direction, typography, palette, spacing, borders, and composition.\n2. Adapt the HTML into the target framework using semantic elements. For React, convert class to className and labels for to htmlFor. No React dependency is included.\n3. Preserve data-dl-element identifiers and their scoped override rules in theme.css. Local overrides intentionally take priority over shared tokens. Reuse the --dl-* tokens for new sections. Keep styles under .dl-site to avoid changing unrelated application UI.\n4. Retain section sizing and the mobile/tablet/desktop grid rules in theme.css. FAQ uses native details/summary; preserve this keyboard-accessible behavior. Preview at 390, 768, and 1440 CSS pixels and at intermediate widths. Do not preserve a desktop overlap when it makes mobile content unreadable.\n5. Replace sample text and assets as needed. Retain image focal points and accessible alternative text.\n6. Connect forms, links, and actions to real application behavior. The example form has no backend. If only some components were exported, update any links pointing to omitted sections. Use unique IDs when repeating fragments.\n7. Test keyboard access, contrast, content reflow, and real device behavior. These style presets are not accessibility certifications.\n\nSelected components: '+t.components.join(', ')+'.\nDirection: '+t.character+'\nFonts use local fallbacks; actual rendering can vary by operating system.\n\nTo preview: run python3 -m http.server 8000 in this folder and open http://localhost:8000.\n';}
async function exportWorkshop(){const status=document.getElementById('export-status'),button=document.getElementById('export-theme');if(!selectedComponents.length)return;button.disabled=true;status.textContent='Preparing your component files…';const t=themeFromState({...state}),components=[...selectedComponents];
try{const [cssResponse,imageResponse,runtimeResponse]=await Promise.all([fetch('workshop.css'),fetch('coast.jpg'),fetch('workshop-runtime.js')]);if(!cssResponse.ok||!imageResponse.ok||!runtimeResponse.ok)throw Error('Asset unavailable');const css=themeVariables(t)+'\n'+await cssResponse.text(),image=new Uint8Array(await imageResponse.arrayBuffer());const html='<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(t.direction)+' theme preview</title><link rel="stylesheet" href="theme.css"><script src="workshop-runtime.js" defer></script></head><body style="margin:0">'+workshopMarkup(t,components)+'</body></html>';const files={'index.html':html,'theme.css':css,'theme.json':JSON.stringify(t,null,2),'CURSOR_HANDOFF.md':exportHandoff(t),'coast.jpg':image,'workshop-runtime.js':await runtimeResponse.text()};
for(const name of components)files['components/'+name+'.html']=componentMarkup(name,t);
const url=URL.createObjectURL(makeComponentZip(files)),a=document.createElement('a');a.href=url;a.download='design-lab-'+t.direction.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='ZIP downloaded. Unzip it and give the folder to Cursor.';}catch{status.textContent='Export failed: a source asset could not be loaded. Please retry when the site is available.';}finally{button.disabled=false;}}

/* Local element rules travel with the shared theme in saved themes and ZIPs. */
let elementOverrides={},selectedElement=null,lastLesson=0;
const editableProperties=['font-family','font-size','font-weight','line-height','letter-spacing','font-kerning','color','background-color','border-radius','padding','object-position','object-fit'];
function validateElementOverrides(input){const out={};if(!input||typeof input!=='object')return out;for(const [id,rules] of Object.entries(input)){if(!Object.keys(componentLabels).some(name=>id.startsWith(name+'-'))||!/^[a-z]+-\d+$/.test(id)||!rules||typeof rules!=='object')continue;for(const [key,value] of Object.entries(rules)){if(editableProperties.includes(key)&&typeof value==='string'&&!/[;{}<>]/.test(value)&&CSS.supports(key,value))(out[id]??={})[key]=value;}}return out;}
function elementOverrideCSS(overrides={}){return Object.entries(validateElementOverrides(overrides)).map(([id,rules])=>'.dl-site [data-dl-element="'+id+'"]{'+Object.entries(rules).map(([key,value])=>key+':'+value+'!important;').join('')+'}').join('\n');}
function setWorkshopMode(enabled){const was=document.body.classList.contains('workshop-mode');if(enabled&&!was)lastLesson=Math.max(0,current-1);document.body.classList.toggle('workshop-mode',enabled);document.getElementById('editor-header').hidden=!enabled;document.querySelector('.editor-label').hidden=!enabled;document.getElementById('element-inspector').hidden=!enabled;if(enabled){if(!was){chooseInspectorPanel('theme');if(innerWidth<=600){document.body.classList.add('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded','false');}}renderElementInspector();}else document.body.classList.remove('inspector-hidden');}
function mountWorkshopSelection(){const doc=previewDocument();if(!doc)return;const style=doc.createElement('style');style.textContent='[data-dl-element]{cursor:pointer}[data-dl-element]:hover{outline:1px dashed #4263eb;outline-offset:3px}[data-dl-selected]{outline:2px solid #4263eb!important;outline-offset:4px}';doc.head.append(style);doc.addEventListener('keydown',e=>{if(!testInteractions&&(e.key==='Enter'||e.key===' ')&&e.target.closest('[data-dl-element]'))selectWorkshopElement(e);});markSelectedElement();renderElementInspector();renderLayoutInspector();setInteractionMode(testInteractions);mountComponentInteractions(doc);}
function markSelectedElement(){const doc=previewDocument();doc?.querySelectorAll('[data-dl-selected]').forEach(el=>el.removeAttribute('data-dl-selected'));const el=doc?.querySelector('[data-dl-element="'+selectedElement+'"]');if(el)el.setAttribute('data-dl-selected','');}
function selectWorkshopElement(e){const el=e.target.closest('[data-dl-element]');if(!el)return;if(el.tagName!=='SUMMARY')e.preventDefault();selectedElement=el.dataset.dlElement;layoutComponent=el.closest('[data-dl-component]').dataset.dlComponent;chooseInspectorPanel('element');document.querySelector('.controls').scrollTop=0;document.body.classList.remove('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded','true');markSelectedElement();renderElementInspector();fitPreview();}
function renderElementInspector(){const box=document.getElementById('element-inspector');if(!box)return;const el=previewQuery('[data-dl-element="'+selectedElement+'"]');if(!el){box.innerHTML='<h3>Element styles</h3><p class="export-note">Click a heading, link, logo, button, image, or section in the preview. Changes here apply only to that element.</p>';return;}const css=el.ownerDocument.defaultView.getComputedStyle(el),rules=elementOverrides[selectedElement]||{};
const number=(key,label,min,max,step,unit)=>'<label>'+label+'<input data-style="'+key+'" data-unit="'+unit+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(parseFloat(rules[key]||css.getPropertyValue(key))||0)+'"></label>';
const select=(key,label,options)=>'<label>'+label+'<select data-style="'+key+'">'+options.map(([v,l])=>'<option value="'+esc(v)+'" '+((rules[key]||css.getPropertyValue(key))===v?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>';
box.innerHTML='<h3>Selected: '+esc(el.tagName.toLowerCase())+'</h3><p class="export-note">'+esc((el.textContent.trim()||el.getAttribute('alt')||'Section').slice(0,65))+' · '+esc(selectedElement)+'</p><button id="edit-section-layout">Edit section layout</button> <button id="select-parent">Select parent section</button><div class="element-fields">'+select('font-family','Font',[['','Inherited / theme'],...Object.entries(systemFaceStack).map(([label,v])=>[v,label])])+number('font-size','Font size',8,180,1,'px')+number('line-height','Leading (line height)',8,240,1,'px')+number('letter-spacing','Tracking (letter spacing)',-5,20,.1,'px')+select('font-kerning','Kerning',[['auto','Auto'],['normal','Normal'],['none','None']])+select('font-weight','Weight',[['400','Regular'],['500','Medium'],['600','Semibold'],['700','Bold'],['800','Extra bold']])+number('border-radius','Corner radius',0,200,1,'px')+number('padding','Padding',0,160,1,'px')+'<label>Text color<input data-style="color" type="color" value="'+cssColorHex(css.color)+'"></label><label>Background<input data-style="background-color" type="color" value="'+cssColorHex(css.backgroundColor)+'"></label>'+(el.tagName==='IMG'?select('object-fit','Image fit',[['cover','Cover'],['contain','Contain'],['fill','Fill']])+'<label>Focal point<input data-style="object-position" type="text" value="'+esc(css.objectPosition)+'" placeholder="50% 50%"></label>':'')+'</div><p class="export-note">Leading and tracking use CSS pixels. Kerning enables the font’s built-in letter-pair spacing. Local styles override the shared theme at every viewport.</p><button id="reset-element">Reset this element</button>'+ (el.matches('.dl-button')?'<button id="apply-all-buttons">Apply these styles to all buttons</button><button id="reset-all-buttons">Reset shared button styles</button>':'') +'<p id="element-status" role="status" class="export-note"></p>';
box.querySelector('#edit-section-layout').onclick=()=>{chooseInspectorPanel('layout');renderLayoutInspector();};
box.querySelector('#select-parent').onclick=()=>{const parent=el.parentElement.closest('section,header,article');if(parent){selectedElement=parent.dataset.dlElement;markSelectedElement();renderElementInspector();}};
if(el.matches('.dl-button')){box.querySelector('#apply-all-buttons').onclick=()=>{if(!Object.keys(validateButtonStyles(elementOverrides[selectedElement])).length){box.querySelector('#element-status').textContent='Change a button style first, then apply it to all buttons.';return;}sharedButtonOverrides={...validateButtonStyles(sharedButtonOverrides),...validateButtonStyles(elementOverrides[selectedElement])};for(const name of Object.keys(componentLabels)){const template=document.createElement('template');template.innerHTML=componentMarkup(name,themeFromState(state));for(const button of template.content.querySelectorAll('.dl-button')){const id=button.dataset.dlElement;for(const key of Object.keys(sharedButtonOverrides))if(elementOverrides[id])delete elementOverrides[id][key];}}applyElementRules();renderElementInspector();box.querySelector('#element-status').textContent='Styles applied to all theme buttons, including components added later.';};box.querySelector('#reset-all-buttons').onclick=()=>{sharedButtonOverrides={};applyElementRules();renderElementInspector();};}
box.querySelector('#reset-element').onclick=()=>{delete elementOverrides[selectedElement];applyElementRules();renderElementInspector();};
box.querySelectorAll('[data-style]').forEach(input=>input.addEventListener('input',()=>{const key=input.dataset.style;let v=input.value;if(input.type==='number'){if(!input.validity.valid||v==='')return;v+=input.dataset.unit;}if(v&&!CSS.supports(key,v)){box.querySelector('#element-status').textContent='Enter a valid CSS value.';return;}if(v)(elementOverrides[selectedElement]??={})[key]=v;else if(elementOverrides[selectedElement])delete elementOverrides[selectedElement][key];applyElementRules();box.querySelector('#element-status').textContent='Applied to this element.';}));}
function cssColorHex(value){const numbers=value.match(/[\d.]+/g)||[];return '#'+[0,1,2].map(i=>Math.round(Number(numbers[i]||0)).toString(16).padStart(2,'0')).join('');}
function applyElementRules(){const doc=previewDocument();let style=doc.getElementById('element-overrides');if(!style){style=doc.createElement('style');style.id='element-overrides';doc.head.append(style);}style.textContent=elementOverrideCSS(elementOverrides);/* Replace original exported rules too, so resetting removes them. */doc.querySelector('.dl-site')?.previousElementSibling?.remove();const themeStyle=doc.createElement('style');themeStyle.textContent=themeVariables(themeFromState(state));doc.body.prepend(themeStyle);}
document.getElementById('exit-workshop').onclick=()=>initialize(lastLesson);
document.getElementById('toggle-inspector').onclick=()=>{const hidden=document.body.classList.toggle('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded',String(!hidden));fitPreview();};

function chooseInspectorPanel(panel){document.body.dataset.inspectorPanel=panel;document.querySelectorAll('[data-panel]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.panel===panel)));}
document.getElementById('inspector-tabs').addEventListener('click',e=>{const button=e.target.closest('[data-panel]');if(button)chooseInspectorPanel(button.dataset.panel);});

/* Shared palette roles and editable section composition. */
let sectionSettings={},layoutComponent='hero',sharedButtonOverrides={},testInteractions=false;
const componentVariants={navigation:['Split','Centered','Hamburger dropdown','Hamburger drawer','Mobile hamburger'],hero:['Preset','Split','Stack','Background image','Text only'],cards:['Filled','Outline'],overlap:['Overlap','Side by side'],form:['Standard'],announcement:['Solid','Outline'],features:['Cards','Plain'],gallery:['Grid','Mosaic'],testimonials:['Cards','Quotes'],pricing:['Cards','Featured'],stats:['Cards','Minimal'],faq:['Accordion','Expanded'],cta:['Solid','Outline'],footer:['Columns','Compact'],slideshow:['Standard','Caption overlay'],lightbox:['Grid','Framed']};
const gridComponents=['cards','features','gallery','testimonials','pricing','stats','lightbox'];
function layoutDefaults(name){return {width:'contained',maxWidth:1240,gutter:24,height:'content',customHeight:580,variant:componentVariants[name]?.[0]||'Standard',desktopColumns:3,tabletColumns:2,mobileColumns:1,columnGap:24,rowGap:24,alignment:'start',gridMode:'fixed',minCardWidth:240,proportion:'balanced'};}
function validateSectionSettings(value){const out={};if(!value||typeof value!=='object')return out;for(const name of Object.keys(componentLabels)){const v=value[name];if(!v||typeof v!=='object')continue;const d=layoutDefaults(name);for(const key of Object.keys(d)){if(typeof d[key]==='number'){const limits={maxWidth:[320,1920],gutter:[0,100],customHeight:[200,1200],desktopColumns:[1,6],tabletColumns:[1,6],mobileColumns:[1,3],columnGap:[0,100],rowGap:[0,100],minCardWidth:[120,600]}[key];if(Number.isFinite(v[key])&&v[key]>=limits[0]&&v[key]<=limits[1])d[key]=Math.round(v[key]);}else {const options={width:['contained','full'],height:['content','custom','screen'],variant:componentVariants[name],alignment:['start','center','end'],gridMode:['fixed','auto'],proportion:['balanced','image-wide','text-wide']}[key];if(options?.includes(v[key]))d[key]=v[key];}}out[name]=d;}return out;}
function layoutFor(name,settings=sectionSettings){return {...layoutDefaults(name),...(validateSectionSettings(settings)[name]||{})};}
function sectionSettingsCSS(settings={}){let css='';for(const name of Object.keys(componentLabels)){const s=layoutFor(name,settings),scope='.dl-component[data-dl-component="'+name+'"]';css+=scope+'{--dl-content-max:'+s.maxWidth+'px;--dl-gutter:'+s.gutter+'px;--dl-section-height:'+s.customHeight+'px;--dl-grid-columns:'+s.desktopColumns+';--dl-column-gap:'+s.columnGap+'px;--dl-row-gap:'+s.rowGap+'px;--dl-card-min:'+s.minCardWidth+'px;--dl-alignment:'+s.alignment+';}';if(s.gridMode==='auto')css+=scope+' .dl-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,var(--dl-card-min)),1fr));}';if(name==='hero'&&s.proportion!=='balanced')css+='@media(min-width:1000px){'+scope+' .dl-hero-split{grid-template-columns:'+(s.proportion==='image-wide'?'1fr 2fr':'2fr 1fr')+';}}';css+='@media(min-width:600px) and (max-width:999px){'+scope+'{--dl-grid-columns:'+s.tabletColumns+';}}@media(max-width:599px){'+scope+'{--dl-grid-columns:'+s.mobileColumns+';}}';}return css;}
function paletteDefaults(p){return {brand:p.brand,secondary:({Editorial:'#315e59',Bauhaus:'#2657ac',Memphis:'#e95c97',Synthwave:'#9228c0',Vaporwave:'#60b6b6',Y2K:'#7893cf'})[p.name]||complementaryColor(p.brand),background:p.bg,surface:p.paper,textColor:p.ink,borderColor:mixHex(p.ink,p.bg,.25)};}
function mixHex(a,b,weight){const parse=c=>c.match(/[0-9a-f]{2}/gi).map(x=>parseInt(x,16));const aa=parse(a),bb=parse(b);return '#'+aa.map((x,i)=>Math.round(x*weight+bb[i]*(1-weight)).toString(16).padStart(2,'0')).join('');}
function complementaryColor(hex){const rgb=hex.match(/[0-9a-f]{2}/gi).map(v=>parseInt(v,16)/255),max=Math.max(...rgb),min=Math.min(...rgb),delta=max-min;if(delta<.05)return '#63758a';let h=0;if(delta){h=max===rgb[0]?(rgb[1]-rgb[2])/delta:max===rgb[1]?(rgb[2]-rgb[0])/delta+2:(rgb[0]-rgb[1])/delta+4;h=(h*60+180+360)%360;}const saturation=.55,lightness=.45,c=(1-Math.abs(2*lightness-1))*saturation,x=c*(1-Math.abs((h/60)%2-1)),m=lightness-c/2;const rgb2=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+rgb2.map(v=>Math.round((v+m)*255).toString(16).padStart(2,'0')).join('');}
function generatePalette(){const p=presetByName(state.direction),dark=luminance(p.bg)<.25,base=dark?'#0c1018':'#ffffff';state.background=mixHex(state.brand,base,dark?.14:.06);state.surface=mixHex(state.brand,dark?'#202632':'#ffffff',dark?.14:.02);state.secondary=complementaryColor(state.brand);state.textColor=['#171b24','#ffffff'].sort((a,b)=>Math.min(ratio(b,state.background),ratio(b,state.surface))-Math.min(ratio(a,state.background),ratio(a,state.surface)))[0];state.borderColor=mixHex(state.textColor,state.background,.28);renderLesson();}
function renderPaletteTools(s){const box=document.getElementById('palette-tools');box.hidden=false;const t=themeFromState(s).tokens;const pair=(label,a,b)=>label+': '+ratio(a,b).toFixed(2)+':1'+(ratio(a,b)<4.5?' · below normal-text AA':'');box.innerHTML='<button id="generate-palette">Generate palette from primary brand</button><p class="export-note">Creates coordinated backgrounds, surfaces, borders, text, and a secondary accent for the selected art direction. You can adjust each color afterward.</p><p class="export-note" role="status">'+esc([pair('Text / page',t.text,t.background),pair('Text / surface',t.text,t.surface),pair('Button text / primary',t.onBrand,t.brand),pair('Links / page',t.brand,t.background)].join(' · '))+'</p>';box.querySelector('button').onclick=generatePalette;}
function libraryMarkup(name,t,s,original){const image=(alt='Red lighthouse above a rocky coast at sunset.')=>'<img src="coast.jpg" alt="'+alt+'" loading="lazy">',card=(h,p)=>'<article class="dl-card"><h3>'+h+'</h3><p>'+p+'</p></article>',grid=(heading,items)=>'<section class="dl-section"><h2>'+heading+'</h2><div class="dl-grid">'+items.join('')+'</div></section>';let h=original;
if(name==='hero'){const v=s.variant==='Preset'?t.composition.hero:s.variant==='Background image'?'overlay':s.variant==='Text only'?'text':s.variant.toLowerCase();h=original.replace(/dl-hero-(split|stack|overlay)/,'dl-hero-'+v);if(v==='text')h=h.replace(/<img[^>]+>/,'');}
if(name==='navigation'&&s.variant.includes('hamburger')||name==='navigation'&&s.variant.includes('Hamburger'))h=hamburgerMarkup(s);
if(name==='navigation'&&s.variant==='Centered')h=h.replace('class="dl-nav"','class="dl-nav dl-nav-centered"');
if(name==='overlap'&&s.variant==='Side by side')h=h.replace('class="dl-overlap dl-section"','class="dl-overlap dl-section dl-overlap-side"');
if(name==='cards'&&s.variant==='Outline')h=h.replaceAll('class="dl-card"','class="dl-card dl-card-outline"');
if(name==='announcement')h='<aside class="dl-announcement '+(s.variant==='Outline'?'dl-outline':'')+'" aria-label="Announcement"><p>Make time for something creative.</p><a href="#dl-workshops">Explore the workshops →</a></aside>';
if(name==='features')h=grid('A little room to explore.',['Small groups','Time to experiment','Something to take home'].map((label,i)=>'<article class="dl-card '+(s.variant==='Plain'?'dl-card-plain':'')+'"><span class="dl-feature-icon" aria-hidden="true">'+['✦','◉','◇'][i]+'</span><h3>'+label+'</h3><p>Learn together, follow your curiosity, and make something of your own.</p></article>'));
if(name==='gallery')h='<section class="dl-section"><h2>Along the coast.</h2><div class="dl-grid '+(s.variant==='Mosaic'?'dl-gallery-mosaic':'')+'">'+['A new perspective','Room to breathe','Follow the light','Stay curious','Take your time','Meet by the water'].map((label,i)=>'<figure class="dl-gallery-item">'+image()+'<figcaption>'+label+'</figcaption></figure>').join('')+'</div><p class="dl-form-note">Gallery uses repeated sample photography; replace with your own images.</p></section>';
if(name==='testimonials')h=grid('What people are saying.',['A lovely space to try something new.','I left with a fresh perspective.','There was time to slow down and learn.'].map((quote,i)=>'<figure class="dl-card '+(s.variant==='Quotes'?'dl-card-plain':'')+'"><blockquote><p>“'+quote+'”</p></blockquote><figcaption>Example participant '+(i+1)+'</figcaption></figure>'));
if(name==='pricing')h=grid('Choose your experience.',['Taster','Full day','Weekend'].map((label,i)=>'<article class="dl-card '+(s.variant==='Featured'&&i===1?'dl-pricing-featured':'')+'"><p class="dl-kicker">'+(i===1&&s.variant==='Featured'?'FEATURED OPTION':'WORKSHOP PACKAGE')+'</p><h3>'+label+'</h3><p class="dl-price">$'+[35,90,160][i]+'</p><p>Example pricing for an experience at your own pace.</p><a class="dl-button" href="#dl-contact">Ask about '+label.toLowerCase()+'</a></article>'));
if(name==='stats')h=grid('Space for new ideas.',['12 places','3 workshops','1 coastline'].map(label=>card(label,'Illustrative workshop details.')));if(name==='stats'&&s.variant==='Minimal')h=h.replaceAll('class="dl-card"','class="dl-card dl-card-plain"');
if(name==='faq')h='<section class="dl-section dl-faq"><h2>A few questions.</h2>'+[['Do I need experience?','No prior experience is needed. Bring your curiosity.'],['What should I bring?','A notebook and comfortable clothing are a good start.'],['How do I book?','Get in touch to ask about dates and availability.']].map(([q,a])=>'<details '+(s.variant==='Expanded'?'open':'')+'><summary>'+q+'</summary><p>'+a+'</p></details>').join('')+'</section>';
if(name==='cta')h='<section class="dl-cta '+(s.variant==='Outline'?'dl-outline':'')+'"><h2>Make room for your next idea.</h2><p>A little time, a new skill, a different view.</p><a class="dl-button" href="#dl-contact">Get in touch</a></section>';
if(name==='footer')h='<footer class="dl-footer '+(s.variant==='Compact'?'dl-footer-compact':'')+'"><div><a class="dl-logo" href="#dl-home">Coastal Weekends</a><p>Follow your curiosity.</p></div><nav aria-label="Footer navigation"><a href="#dl-workshops">Workshops</a><a href="#dl-contact">Get in touch</a></nav><p class="dl-form-note">Example website theme · Built with care.</p></footer>';
if(name==='slideshow')h=slideshowMarkup(s);if(name==='lightbox')h=lightboxMarkup(s);
return h;}
function renderLayoutInspector(){const box=document.getElementById('layout-inspector');if(!box)return;box.hidden=false;if(!selectedComponents.includes(layoutComponent))layoutComponent=selectedComponents[0]||'hero';const name=layoutComponent,s=layoutFor(name);const select=(key,label,options)=>'<label>'+label+'<select data-layout="'+key+'">'+options.map(([v,l])=>'<option value="'+v+'" '+(s[key]===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label>';const number=(key,label,min,max)=>'<label>'+label+'<input data-layout="'+key+'" type="number" min="'+min+'" max="'+max+'" value="'+s[key]+'"></label>';
box.innerHTML='<button id="open-library">Browse all '+Object.keys(componentLabels).length+' components</button><h3>Section layout</h3><div class="element-fields"><label>Component<select id="layout-component">'+selectedComponents.map(n=>'<option value="'+n+'" '+(name===n?'selected':'')+'>'+componentLabels[n]+'</option>').join('')+'</select></label>'+select('variant','Variation',componentVariants[name].map(v=>[v,v]))+select('width','Section width',[['contained','Contained'],['full','Full width / full bleed']])+number('maxWidth','Content maximum width (px)',320,1920)+number('gutter','Side gutters (px)',0,100)+(['hero','cta','overlap'].includes(name)?select('height','Section height',[['content','Content sized'],['custom','Custom minimum'],['screen','Screen height minimum']])+number('customHeight','Custom minimum height (px)',200,1200):'')+(name==='hero'?select('proportion','Split proportions',[['balanced','Balanced'],['image-wide','⅓ text / ⅔ image'],['text-wide','⅔ text / ⅓ image']]):'')+(gridComponents.includes(name)?select('gridMode','Grid mode',[['fixed','Columns per viewport'],['auto','Auto fit by minimum card width']])+number('desktopColumns','Desktop columns',1,6)+number('tabletColumns','Tablet columns',1,6)+number('mobileColumns','Mobile columns',1,3)+number('minCardWidth','Auto-fit minimum card width (px)',120,600)+number('columnGap','Column gap (px)',0,100)+number('rowGap','Row gap (px)',0,100)+select('alignment','Content alignment',[['start','Left'],['center','Center'],['end','Right']]):'')+'</div><p class="export-note">Device previews use the matching column setting. Full-bleed background heroes extend to the screen edges while their text respects the gutters and maximum width. Heights are minimums so content can grow. Changing a variation resets that component’s local element styles.</p><button id="reset-layout">Reset section layout</button>';
box.querySelector('#open-library').onclick=()=>chooseInspectorPanel('library');
box.querySelectorAll('[data-layout]').forEach(input=>{const key=input.dataset.layout;if(['desktopColumns','tabletColumns','mobileColumns'].includes(key))input.disabled=s.gridMode==='auto';if(key==='minCardWidth')input.disabled=s.gridMode!=='auto';if(key==='customHeight')input.disabled=s.height!=='custom';});
box.querySelector('#layout-component').onchange=e=>{layoutComponent=e.target.value;renderLayoutInspector();};box.querySelector('#reset-layout').onclick=()=>{delete sectionSettings[name];for(const id of Object.keys(elementOverrides))if(id.startsWith(name+'-'))delete elementOverrides[id];selectedElement=null;renderPreview();};
box.querySelectorAll('[data-layout]').forEach(input=>input.addEventListener('change',()=>{if(!input.validity.valid)return;const key=input.dataset.layout,value=input.type==='number'?Number(input.value):input.value;if(key==='variant'&&value!==s.variant){for(const id of Object.keys(elementOverrides))if(id.startsWith(name+'-'))delete elementOverrides[id];selectedElement=null;}sectionSettings[name]={...layoutFor(name),[key]:value};renderPreview();}));}

function validateButtonStyles(value){return validateElementOverrides({'hero-0':value})['hero-0']||{};}
function sharedButtonCSS(value){const rules=validateButtonStyles(value);return '.dl-site .dl-button{'+Object.entries(rules).map(([key,v])=>key+':'+v+'!important;').join('')+'}';}
function setInteractionMode(enabled){testInteractions=enabled;document.getElementById('toggle-interactions').setAttribute('aria-pressed',String(enabled));document.getElementById('toggle-interactions').textContent=enabled?'Back to editing':'Test interactions';document.querySelector('#editor-header>span').textContent=enabled?'Test menus, slides, and images':'Click an element to style it';const doc=previewDocument();if(doc?.body)doc.body.dataset.dlEditing=String(!enabled);}
document.getElementById('toggle-interactions').onclick=()=>setInteractionMode(!testInteractions);
function hamburgerMarkup(s){const variant=s.variant==='Hamburger drawer'?'dl-menu-drawer':s.variant==='Mobile hamburger'?'dl-menu-mobile':'dl-menu-dropdown';return '<header class="dl-nav dl-nav-menu '+variant+'"><a class="dl-logo" href="#dl-home">Coastal Weekends</a><button class="dl-menu-toggle" type="button" data-dl-action="menu" aria-expanded="false" aria-controls="dl-menu-links" aria-label="Toggle navigation"><span></span><span></span><span></span></button><button class="dl-menu-backdrop" type="button" data-dl-action="close-menu" aria-label="Close navigation" hidden></button><nav id="dl-menu-links" aria-label="Main navigation" hidden><a href="#dl-workshops">Workshops</a><a href="#dl-contact">Get in touch</a></nav></header>';}
function slideshowMarkup(s){return '<section class="dl-section dl-slideshow '+(s.variant==='Caption overlay'?'dl-slide-overlay':'')+'" aria-label="Coastal slideshow" aria-roledescription="carousel" tabindex="0"><h2>A change of perspective.</h2>'+['By the water','Follow the light','A little room to breathe'].map((label,i)=>'<figure data-slide '+(i?'hidden':'')+' role="group" aria-roledescription="slide" aria-label="'+(i+1)+' of 3"><img src="coast.jpg" alt="Red lighthouse and rocky coast at sunset." loading="lazy" style="object-position:'+[15,50,85][i]+'% 50%"><figcaption>'+label+'</figcaption></figure>').join('')+'<div class="dl-slide-controls"><button type="button" class="dl-button" data-dl-action="previous" aria-label="Previous slide">← Previous</button><span data-slide-status role="status" aria-live="polite">Slide 1 of 3</span><button type="button" class="dl-button" data-dl-action="next" aria-label="Next slide">Next →</button></div><p class="dl-form-note">Manual slideshow: use the buttons or arrow keys. Sample slides reuse the local photograph.</p></section>';}
function lightboxMarkup(s){return '<section class="dl-section dl-lightbox '+(s.variant==='Framed'?'dl-lightbox-framed':'')+'"><h2>Take a closer look.</h2><div class="dl-grid">'+['Coastal light','A rocky shoreline','Room for discovery'].map((label,i)=>'<button type="button" class="dl-lightbox-trigger" data-dl-action="lightbox" data-caption="'+label+'" aria-label="Enlarge '+label.toLowerCase()+'"><img src="coast.jpg" alt="Red lighthouse and rocky coast at sunset." loading="lazy" style="object-position:'+[15,50,85][i]+'% 50%"><span>'+label+'</span></button>').join('')+'</div><dialog aria-label="Enlarged coastal photograph"><button type="button" class="dl-button" data-dl-action="close-lightbox" autofocus>Close image</button><img src="coast.jpg" alt=""><p data-lightbox-caption></p></dialog><p class="dl-form-note">Select a photo to enlarge it. Escape closes the image.</p></section>';}
