/* Original preset interpretations: no external fonts or runtime dependencies. */
const designPresets=[
{name:'Editorial',family:'Modern',bg:'#f6f2ea',paper:'#ffffff',ink:'#252321',brand:'#853224',font:'Georgia, serif',body:'system-ui, sans-serif',radius:2,space:30,layout:'split',character:'Serif headlines, measured spacing, a strong reading rhythm.'},
{name:'Playful',family:'Modern',bg:'#fff1a8',paper:'#ffffff',ink:'#202052',brand:'#b11b61',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:24,space:24,layout:'split',character:'Rounded shapes, lively color, an offset image frame.'},
{name:'Minimal',family:'Modern',bg:'#ffffff',paper:'#f6f6f6',ink:'#181818',brand:'#282828',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:40,layout:'split',character:'Restrained typography, generous space, simple surfaces.'},
{name:'Dramatic',family:'Modern',bg:'#101827',paper:'#1e293b',ink:'#f8fafc',brand:'#ff946e',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:32,layout:'overlay',character:'Dark surfaces, oversized headings, an atmospheric image.'},
{name:'Material-inspired',family:'Modern',bg:'#f3f0fc',paper:'#ffffff',ink:'#251d36',brand:'#6342a6',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:24,space:24,layout:'split',character:'Rounded surfaces, clear emphasis, comfortable controls.'},
{name:'Glassmorphism',family:'Modern',bg:'#182343',paper:'#263352',ink:'#ffffff',brand:'#8fc9ff',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:20,space:28,layout:'overlay',character:'Translucent panels, subtle borders, layered backgrounds.'},
{name:'Luxury',family:'Modern',bg:'#141414',paper:'#24221d',ink:'#f6ecd5',brand:'#dfc181',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:40,layout:'split',character:'Fine borders, warm metallic accents, spacious serif type.'},
{name:'Nordic',family:'Modern',bg:'#eef3f2',paper:'#ffffff',ink:'#243635',brand:'#315e59',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:4,space:36,layout:'split',character:'Quiet surfaces, practical typography, natural colors.'},
{name:'Brutalist',family:'Experimental',bg:'#ffffff',paper:'#ffffff',ink:'#111111',brand:'#0000bb',font:'ui-monospace, monospace',body:'ui-monospace, monospace',radius:0,space:16,layout:'stack',character:'Exposed structure, obvious links, blunt typography.'},
{name:'Neo-brutalist',family:'Experimental',bg:'#faf1bd',paper:'#ffffff',ink:'#151515',brand:'#6742ba',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:24,layout:'split',character:'Thick outlines, hard shadows, assertive color blocks.'},
{name:'Collage',family:'Experimental',bg:'#f6dfcb',paper:'#fff9ed',ink:'#342a27',brand:'#9c3229',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:26,layout:'split',character:'Tilted imagery, layered captions, a cut-paper feeling.'},
{name:'Bauhaus',family:'Historical',bg:'#f6efdd',paper:'#fffdf4',ink:'#202126',brand:'#ba2727',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:0,space:28,layout:'split',character:'Geometric structure, primary-color accents, strong asymmetry.'},
{name:'Swiss International',family:'Historical',bg:'#ffffff',paper:'#f3f3f3',ink:'#171717',brand:'#bd2525',font:'Arial, Helvetica, sans-serif',body:'Arial, Helvetica, sans-serif',radius:0,space:32,layout:'split',character:'An orderly grid, left alignment, disciplined sans-serif type.'},
{name:'Art Deco',family:'Historical',bg:'#172a2e',paper:'#20363a',ink:'#f7edcf',brand:'#e5c775',font:'Georgia, serif',body:'system-ui, sans-serif',radius:0,space:32,layout:'stack',character:'Symmetry, fine geometric borders, a gold-accented palette.'},
{name:'Memphis',family:'Historical',bg:'#ffe7ec',paper:'#ffffff',ink:'#26214b',brand:'#68329f',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:8,space:24,layout:'split',character:'Bold outlines, contrasting pastels, patterned surfaces.'},
{name:'Early web',family:'Retro digital',bg:'#d6d6d6',paper:'#ffffff',ink:'#000000',brand:'#000099',font:'Times New Roman, serif',body:'Arial, sans-serif',radius:0,space:16,layout:'stack',character:'Beveled surfaces, underlined links, browser-era typography.'},
{name:'Terminal',family:'Retro digital',bg:'#07150b',paper:'#102119',ink:'#bef5c6',brand:'#77ed94',font:'ui-monospace, monospace',body:'ui-monospace, monospace',radius:0,space:20,layout:'stack',character:'Monospace type, green accents, explicit structural borders.'},
{name:'Y2K',family:'Retro digital',bg:'#e6edff',paper:'#ffffff',ink:'#162452',brand:'#244ec0',font:'Arial, sans-serif',body:'Arial, sans-serif',radius:18,space:24,layout:'split',character:'Glossy gradients, silver-blue surfaces, rounded capsules.'},
{name:'Synthwave',family:'Retro digital',bg:'#180b33',paper:'#281345',ink:'#fbedff',brand:'#ff92d0',font:'system-ui, sans-serif',body:'system-ui, sans-serif',radius:4,space:28,layout:'overlay',character:'Neon accents, dark violet surfaces, a grid-like background.'},
{name:'Vaporwave',family:'Retro digital',bg:'#f4d5f3',paper:'#ffeefc',ink:'#462857',brand:'#702a91',font:'Georgia, serif',body:'ui-monospace, monospace',radius:2,space:28,layout:'split',character:'Pastel gradients, nostalgic serif type, tinted imagery.'}
];
let selectedComponents=['navigation','hero','cards','form','overlap'];
const componentLabels={navigation:'Navigation',hero:'Hero',cards:'Cards',form:'Form',overlap:'Image + text overlap'};
function presetByName(name){return designPresets.find(p=>p.name===name)||designPresets[0];}
function directionOptions(){return [...new Set(designPresets.map(p=>p.family))].map(f=>({label:f,items:designPresets.filter(p=>p.family===f).map(p=>p.name)}));}
function createWorkshopLesson(){return{group:'Build a theme',title:'Theme workshop',description:'Choose a visual direction, customize its shared settings, and test the same components at mobile, tablet, and desktop widths. Select the components you want and export their HTML, styles, assets, and a Cursor handoff. These are editable interpretations of design styles, not official standards.',challenge:'Choose a direction, inspect it at all three widths, then select only the components you want to export.',notice:'The export uses the same HTML and styles as this preview. Shared tokens guide new components; composition rules preserve the direction. Forms and calls to action are visual examples that need application behavior when integrated.',controls:[select('direction','Art direction',directionOptions(),'Editorial'),color('brand','Brand color','#853224'),select('headingFont','Heading font',['Preset default',...Object.keys(systemFaceStack)],'Preset default'),range('fontScale','Type scale',.8,1.4,1,'×',.05),range('spacing','Spacing',12,48,30,'px'),range('radius','Corners',0,32,2,'px'),select('layout','Hero arrangement',['Preset default','Split','Stack','Overlay'],'Preset default'),range('overlap','Image overlap',0,100,36,'px')],kind:'workshop'};}
function themeFromState(s){const p=presetByName(s.direction);const brand=s.brand||p.brand;return {schemaVersion:2,elementOverrides:JSON.parse(JSON.stringify(elementOverrides)),direction:p.name,family:p.family,character:p.character,tokens:{background:p.bg,surface:p.paper,text:p.ink,brand,onBrand:ratio('#ffffff',brand)>=ratio('#111111',brand)?'#ffffff':'#111111',headingFont:s.headingFont&&s.headingFont!=='Preset default'?(systemFaceStack[s.headingFont]||p.font):p.font,bodyFont:p.body,radius:Number(s.radius??s.round??p.radius),spacing:Number(s.spacing??p.space),fontScale:Number(s.fontScale??1)},composition:{hero:s.layout&&s.layout!=='Preset default'?s.layout.toLowerCase():p.layout,overlap:Number(s.overlap??36)},responsive:{mobileMax:599,tabletMax:999,desktopMin:1000},components:[...selectedComponents]};}
function themeVariables(t){const c=t.tokens;return '.dl-site{--dl-bg:'+c.background+';--dl-surface:'+c.surface+';--dl-text:'+c.text+';--dl-brand:'+c.brand+';--dl-on-brand:'+c.onBrand+';--dl-heading-font:'+c.headingFont+';--dl-body-font:'+c.bodyFont+';--dl-radius:'+c.radius+'px;--dl-space:'+c.spacing+'px;--dl-scale:'+c.fontScale+';--dl-overlap:'+t.composition.overlap+'px;}'+elementOverrideCSS(t.elementOverrides);}
function componentMarkup(name,t){const img='<img src="coast.jpg" alt="Red lighthouse above a rocky coast at sunset." loading="lazy">';const names={navigation:'<header class="dl-nav"><a class="dl-logo" href="#dl-home">Coastal Weekends</a><nav aria-label="Main navigation"><a href="#dl-workshops">Workshops</a><a href="#dl-contact">Get in touch</a></nav></header>',hero:'<section id="dl-home" class="dl-hero dl-hero-'+t.composition.hero+'"><div class="dl-hero-copy"><p class="dl-kicker">MAKE ROOM FOR SOMETHING NEW</p><h1>Find a little perspective.</h1><p>A slower day by the sea. A little room for a new idea.</p><a class="dl-button" href="#dl-workshops">Explore workshops</a></div>'+img+'</section>',cards:'<section id="dl-workshops" class="dl-section"><h2>Choose your next chapter.</h2><div class="dl-grid">'+['Creative writing','Photography','Printmaking'].map((name,i)=>'<article class="dl-card"><p class="dl-kicker">WORKSHOP 0'+(i+1)+'</p><h3>'+name+'</h3><p>Explore a new skill at your own pace.</p><a href="#dl-contact">Ask about this workshop</a></article>').join('')+'</div></section>',form:'<section id="dl-contact" class="dl-section"><h2>Stay in the loop.</h2><form class="dl-form"><div><label for="dl-name">Your name</label><input id="dl-name" name="name" autocomplete="name" required></div><div><label for="dl-email">Email address</label><input id="dl-email" name="email" type="email" autocomplete="email" required></div><button class="dl-button" type="submit">Request information</button><p class="dl-form-note">Example form: connect submission behavior in your application.</p></form></section>',overlap:'<section class="dl-overlap dl-section">'+img+'<div class="dl-overlap-copy"><p class="dl-kicker">A DIFFERENT POINT OF VIEW</p><h2>Meet me by the water.</h2><p>Follow the coast. Leave room for discovery.</p></div></section>'};const template=document.createElement('template');template.innerHTML=names[name]||'';template.content.querySelectorAll('header,nav,section,article,div,a,h1,h2,h3,p,img,label,input,button,form').forEach((el,i)=>el.setAttribute('data-dl-element',name+'-'+i));return template.innerHTML;}
function workshopMarkup(t,components=selectedComponents){return '<div class="dl-site dl-'+t.direction.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'">'+components.map(n=>componentMarkup(n,t)).join('')+'</div>';}
function renderWorkshop(s,components=selectedComponents){const t=themeFromState(s);return {h:'<style>'+themeVariables(t)+'</style>'+workshopMarkup(t,components),style:'',extra:''};}
function showWorkshopTools(kind,s){const box=document.getElementById('workshop-tools');box.hidden=kind!=='workshop';if(kind!=='workshop')return;document.querySelector('.controls').append(box);const p=presetByName(s.direction);box.className='workshop-tools';box.innerHTML='<div class="style-summary"><strong>'+esc(p.family)+' · '+esc(p.name)+'</strong><p>'+esc(p.character)+'</p></div><fieldset style="border:0;padding:0;margin:0"><legend style="font-size:14px;font-weight:600">Components to preview and export</legend><div class="component-choices">'+Object.entries(componentLabels).map(([k,label])=>'<label><input type="checkbox" data-component="'+k+'" '+(selectedComponents.includes(k)?'checked':'')+'> '+label+'</label>').join('')+'</div></fieldset><div class="export-actions"><button id="export-theme" class="export-primary" '+(!selectedComponents.length?'disabled':'')+'>Export component ZIP</button><button id="save-theme">Save on this device</button><button id="load-theme">Load saved theme</button></div><p class="export-note">HTML components + shared CSS + theme.json + image + CURSOR_HANDOFF.md. These are portable source files, not screenshots.</p><p id="export-status" class="export-note" role="status"></p>';
box.querySelectorAll('[data-component]').forEach(c=>c.addEventListener('change',()=>{selectedComponents=Object.keys(componentLabels).filter(k=>box.querySelector('[data-component="'+k+'"]').checked);renderPreview();}));
box.querySelector('#export-theme').onclick=exportWorkshop;
box.querySelector('#save-theme').onclick=()=>{try{localStorage.setItem('design-lab-theme-v1',JSON.stringify({state,components:selectedComponents,elementOverrides}));document.getElementById('export-status').textContent='Theme saved on this device.';}catch{document.getElementById('export-status').textContent='Saving is unavailable in this browser. Export the ZIP instead.';}};
box.querySelector('#load-theme').onclick=()=>{try{const saved=JSON.parse(localStorage.getItem('design-lab-theme-v1'));if(!saved)throw Error('No saved theme');const lesson=lessons[current],next={};for(const c of lesson.controls){const v=saved.state?.[c.key];if(c.type==='range'){if(typeof v!=='number'||!Number.isFinite(v)||v<c.min||v>c.max)throw Error('Invalid saved value');}else if(c.type==='color'){if(!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid color');}else if(c.type==='select'){const options=c.options.flatMap(o=>typeof o==='string'?[o]:o.items);if(!options.includes(v))throw Error('Invalid selection');}next[c.key]=v;}state=next;elementOverrides=validateElementOverrides(saved.elementOverrides);selectedElement=null;selectedComponents=Array.isArray(saved.components)?Object.keys(componentLabels).filter(k=>saved.components.includes(k)):Object.keys(componentLabels);renderLesson();document.getElementById('export-status').textContent='Saved theme loaded.';}catch{document.getElementById('export-status').textContent='No compatible saved theme on this device.';}};
}
/* Small, dependency-free ZIP writer using stored entries and CRC32. */
const zipCrcTable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function zipCrc(bytes){let n=0xffffffff;for(const b of bytes)n=zipCrcTable[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;}
function makeComponentZip(files){const enc=new TextEncoder(),chunks=[],central=[];let offset=0;for(const [path,value] of Object.entries(files)){const name=enc.encode(path),bytes=typeof value==='string'?enc.encode(value):value,crc=zipCrc(bytes);const local=new Uint8Array(30+name.length),lv=new DataView(local.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x0800,true);lv.setUint16(12,33,true);lv.setUint32(14,crc,true);lv.setUint32(18,bytes.length,true);lv.setUint32(22,bytes.length,true);lv.setUint16(26,name.length,true);local.set(name,30);chunks.push(local,bytes);const entry=new Uint8Array(46+name.length),ev=new DataView(entry.buffer);ev.setUint32(0,0x02014b50,true);ev.setUint16(4,20,true);ev.setUint16(6,20,true);ev.setUint16(8,0x0800,true);ev.setUint16(14,33,true);ev.setUint32(16,crc,true);ev.setUint32(20,bytes.length,true);ev.setUint32(24,bytes.length,true);ev.setUint16(28,name.length,true);ev.setUint32(42,offset,true);entry.set(name,46);central.push(entry);offset+=local.length+bytes.length;}
const length=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array(22),dv=new DataView(end.buffer);dv.setUint32(0,0x06054b50,true);dv.setUint16(8,central.length,true);dv.setUint16(10,central.length,true);dv.setUint32(12,length,true);dv.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});}
function exportHandoff(t){return '# Cursor handoff: '+t.direction+'\n\nUse this package as the visual source of truth for the website.\n\n## Files\n- index.html: assembled selected components, matching the Design Lab preview.\n- components/: separate HTML fragments.\n- theme.css: shared tokens and scoped component styles.\n- theme.json: theme settings, composition, responsive breakpoints, and elementOverrides.\n- coast.jpg: local sample image.\n\n## Instructions\n1. Read these files before implementing the website. Preserve the selected direction, typography, palette, spacing, borders, and composition.\n2. Adapt the HTML into the target framework using semantic elements. For React, convert class to className and labels for to htmlFor. No React dependency is included.\n3. Preserve data-dl-element identifiers and their scoped override rules in theme.css. Local overrides intentionally take priority over shared tokens. Reuse the --dl-* tokens for new sections. Keep styles under .dl-site to avoid changing unrelated application UI.\n4. Retain the mobile/tablet/desktop rules in theme.css. Preview at 390, 768, and 1440 CSS pixels and at intermediate widths. Do not preserve a desktop overlap when it makes mobile content unreadable.\n5. Replace sample text and assets as needed. Retain image focal points and accessible alternative text.\n6. Connect forms, links, and actions to real application behavior. The example form has no backend. If only some components were exported, update any links pointing to omitted sections. Use unique IDs when repeating fragments.\n7. Test keyboard access, contrast, content reflow, and real device behavior. These style presets are not accessibility certifications.\n\nSelected components: '+t.components.join(', ')+'.\nDirection: '+t.character+'\nFonts use local fallbacks; actual rendering can vary by operating system.\n\nTo preview: run python3 -m http.server 8000 in this folder and open http://localhost:8000.\n';}
async function exportWorkshop(){const status=document.getElementById('export-status'),button=document.getElementById('export-theme');if(!selectedComponents.length)return;button.disabled=true;status.textContent='Preparing your component files…';const t=themeFromState({...state}),components=[...selectedComponents];
try{const [cssResponse,imageResponse]=await Promise.all([fetch('workshop.css'),fetch('coast.jpg')]);if(!cssResponse.ok||!imageResponse.ok)throw Error('Asset unavailable');const css=themeVariables(t)+'\n'+await cssResponse.text(),image=new Uint8Array(await imageResponse.arrayBuffer());const html='<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(t.direction)+' theme preview</title><link rel="stylesheet" href="theme.css"></head><body style="margin:0">'+workshopMarkup(t,components)+'</body></html>';const files={'index.html':html,'theme.css':css,'theme.json':JSON.stringify(t,null,2),'CURSOR_HANDOFF.md':exportHandoff(t),'coast.jpg':image};
for(const name of components)files['components/'+name+'.html']=componentMarkup(name,t);
const url=URL.createObjectURL(makeComponentZip(files)),a=document.createElement('a');a.href=url;a.download='design-lab-'+t.direction.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='ZIP downloaded. Unzip it and give the folder to Cursor.';}catch{status.textContent='Export failed: a source asset could not be loaded. Please retry when the site is available.';}finally{button.disabled=false;}}

/* Local element rules travel with the shared theme in saved themes and ZIPs. */
let elementOverrides={},selectedElement=null,lastLesson=0;
const editableProperties=['font-family','font-size','font-weight','line-height','letter-spacing','font-kerning','color','background-color','border-radius','padding','object-position','object-fit'];
function validateElementOverrides(input){const out={};if(!input||typeof input!=='object')return out;for(const [id,rules] of Object.entries(input)){if(!/^(navigation|hero|cards|form|overlap)-\d+$/.test(id)||!rules||typeof rules!=='object')continue;for(const [key,value] of Object.entries(rules)){if(editableProperties.includes(key)&&typeof value==='string'&&!/[;{}<>]/.test(value)&&CSS.supports(key,value))(out[id]??={})[key]=value;}}return out;}
function elementOverrideCSS(overrides={}){return Object.entries(validateElementOverrides(overrides)).map(([id,rules])=>'.dl-site [data-dl-element="'+id+'"]{'+Object.entries(rules).map(([key,value])=>key+':'+value+'!important;').join('')+'}').join('\n');}
function setWorkshopMode(enabled){const was=document.body.classList.contains('workshop-mode');if(enabled&&!was)lastLesson=Math.max(0,current-1);document.body.classList.toggle('workshop-mode',enabled);document.getElementById('editor-header').hidden=!enabled;document.querySelector('.editor-label').hidden=!enabled;document.getElementById('element-inspector').hidden=!enabled;if(enabled){if(!was){chooseInspectorPanel('theme');if(innerWidth<=600){document.body.classList.add('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded','false');}}renderElementInspector();}else document.body.classList.remove('inspector-hidden');}
function mountWorkshopSelection(){const doc=previewDocument();if(!doc)return;const style=doc.createElement('style');style.textContent='[data-dl-element]{cursor:pointer}[data-dl-element]:hover{outline:1px dashed #4263eb;outline-offset:3px}[data-dl-selected]{outline:2px solid #4263eb!important;outline-offset:4px}';doc.head.append(style);doc.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-dl-element]'))selectWorkshopElement(e);});markSelectedElement();renderElementInspector();}
function markSelectedElement(){const doc=previewDocument();doc?.querySelectorAll('[data-dl-selected]').forEach(el=>el.removeAttribute('data-dl-selected'));const el=doc?.querySelector('[data-dl-element="'+selectedElement+'"]');if(el)el.setAttribute('data-dl-selected','');}
function selectWorkshopElement(e){const el=e.target.closest('[data-dl-element]');if(!el)return;e.preventDefault();selectedElement=el.dataset.dlElement;chooseInspectorPanel('element');document.querySelector('.controls').scrollTop=0;document.body.classList.remove('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded','true');markSelectedElement();renderElementInspector();fitPreview();}
function renderElementInspector(){const box=document.getElementById('element-inspector');if(!box)return;const el=previewQuery('[data-dl-element="'+selectedElement+'"]');if(!el){box.innerHTML='<h3>Element styles</h3><p class="export-note">Click a heading, link, logo, button, image, or section in the preview. Changes here apply only to that element.</p>';return;}const css=el.ownerDocument.defaultView.getComputedStyle(el),rules=elementOverrides[selectedElement]||{};
const number=(key,label,min,max,step,unit)=>'<label>'+label+'<input data-style="'+key+'" data-unit="'+unit+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(parseFloat(rules[key]||css.getPropertyValue(key))||0)+'"></label>';
const select=(key,label,options)=>'<label>'+label+'<select data-style="'+key+'">'+options.map(([v,l])=>'<option value="'+esc(v)+'" '+((rules[key]||css.getPropertyValue(key))===v?'selected':'')+'>'+esc(l)+'</option>').join('')+'</select></label>';
box.innerHTML='<h3>Selected: '+esc(el.tagName.toLowerCase())+'</h3><p class="export-note">'+esc((el.textContent.trim()||el.getAttribute('alt')||'Section').slice(0,65))+' · '+esc(selectedElement)+'</p><button id="select-parent">Select parent section</button><div class="element-fields">'+select('font-family','Font',[['','Inherited / theme'],...Object.entries(systemFaceStack).map(([label,v])=>[v,label])])+number('font-size','Font size',8,180,1,'px')+number('line-height','Leading (line height)',8,240,1,'px')+number('letter-spacing','Tracking (letter spacing)',-5,20,.1,'px')+select('font-kerning','Kerning',[['auto','Auto'],['normal','Normal'],['none','None']])+select('font-weight','Weight',[['400','Regular'],['500','Medium'],['600','Semibold'],['700','Bold'],['800','Extra bold']])+number('border-radius','Corner radius',0,200,1,'px')+number('padding','Padding',0,160,1,'px')+'<label>Text color<input data-style="color" type="color" value="'+cssColorHex(css.color)+'"></label><label>Background<input data-style="background-color" type="color" value="'+cssColorHex(css.backgroundColor)+'"></label>'+(el.tagName==='IMG'?select('object-fit','Image fit',[['cover','Cover'],['contain','Contain'],['fill','Fill']])+'<label>Focal point<input data-style="object-position" type="text" value="'+esc(css.objectPosition)+'" placeholder="50% 50%"></label>':'')+'</div><p class="export-note">Leading and tracking use CSS pixels. Kerning enables the font’s built-in letter-pair spacing. Local styles override the shared theme at every viewport.</p><button id="reset-element">Reset this element</button><p id="element-status" role="status" class="export-note"></p>';
box.querySelector('#select-parent').onclick=()=>{const parent=el.parentElement.closest('section,header,article');if(parent){selectedElement=parent.dataset.dlElement;markSelectedElement();renderElementInspector();}};
box.querySelector('#reset-element').onclick=()=>{delete elementOverrides[selectedElement];applyElementRules();renderElementInspector();};
box.querySelectorAll('[data-style]').forEach(input=>input.addEventListener('input',()=>{const key=input.dataset.style;let v=input.value;if(input.type==='number'){if(!input.validity.valid||v==='')return;v+=input.dataset.unit;}if(v&&!CSS.supports(key,v)){box.querySelector('#element-status').textContent='Enter a valid CSS value.';return;}if(v)(elementOverrides[selectedElement]??={})[key]=v;else if(elementOverrides[selectedElement])delete elementOverrides[selectedElement][key];applyElementRules();box.querySelector('#element-status').textContent='Applied to this element.';}));}
function cssColorHex(value){const numbers=value.match(/[\d.]+/g)||[];return '#'+[0,1,2].map(i=>Math.round(Number(numbers[i]||0)).toString(16).padStart(2,'0')).join('');}
function applyElementRules(){const doc=previewDocument();let style=doc.getElementById('element-overrides');if(!style){style=doc.createElement('style');style.id='element-overrides';doc.head.append(style);}style.textContent=elementOverrideCSS(elementOverrides);/* Replace original exported rules too, so resetting removes them. */doc.querySelector('.dl-site')?.previousElementSibling?.remove();const themeStyle=doc.createElement('style');themeStyle.textContent=themeVariables(themeFromState(state));doc.body.prepend(themeStyle);}
document.getElementById('exit-workshop').onclick=()=>initialize(lastLesson);
document.getElementById('toggle-inspector').onclick=()=>{const hidden=document.body.classList.toggle('inspector-hidden');document.getElementById('toggle-inspector').setAttribute('aria-expanded',String(!hidden));fitPreview();};

function chooseInspectorPanel(panel){document.body.dataset.inspectorPanel=panel;document.querySelectorAll('[data-panel]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.panel===panel)));}
document.getElementById('inspector-tabs').addEventListener('click',e=>{const button=e.target.closest('[data-panel]');if(button)chooseInspectorPanel(button.dataset.panel);});
